apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  labels:
    app: sonarr
    version: v1
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
      version: v1
  template:
    metadata:
      labels:
        app: sonarr
        version: v1
    spec:
      containers:
      - name: sonarr
        image: alpine:latest
        command: ["sleep"]
        args: ["infinity"]
        volumeMounts:
        - name: config
          mountPath: /config
        - name: config-nas1-mtank
          mountPath: /config-new
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: config-nas1-mtank
        persistentVolumeClaim:
          claimName: config-nas1-mtank
      - name: scratch
        persistentVolumeClaim:
          claimName: scratch
      - name: media
        persistentVolumeClaim:
          claimName: media
