---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-sonarr
  labels:
    app: sonarr
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
