---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 80
      targetPort: http
