# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/snapshot.storage.k8s.io/volumesnapshotcontent_v1.json
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: sonarr-config-restore-content
spec:
  deletionPolicy: Retain
  driver: org.democratic-csi.nas1-mtank-iscsi
  source:
    snapshotHandle: pvc-0b4fab02-96b4-4ee6-a26c-098c5a81a7a1@snapshot-ddbc7eb6-fc2f-4cd5-a72f-57f2782ede0a
  volumeSnapshotClassName: nas1-mtank-iscsi
  volumeSnapshotRef:
    name: sonarr-config-restore
    namespace: sonarr
