# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-api-key
spec:
  itemPath: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/434ts4xjejvfmam472ralbu5yy"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: discord-webhook
spec:
  itemPath: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/za77mjbdgdvzrohyjpzpgiyxva"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qbittorrent
spec:
  itemPath: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/vt4jt6i5jmyzzpi4nb45qbnuqq"
