# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-api-key
spec:
  itemPath: "vaults/copxopw5gkuo2m3cv7acvkrfxy/items/6ok3icedkqfi3fvjko2lpu4ukm"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: discord-webhook
spec:
  itemPath: "vaults/copxopw5gkuo2m3cv7acvkrfxy/items/z3524tyqwjg4dk2rx3zx5k63ma"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qbittorrent
spec:
  itemPath: "vaults/copxopw5gkuo2m3cv7acvkrfxy/items/zkwm3ar2obivwfe2ni6dyxturu"
