---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    flux.weave.works/automated: 'false'
spec:
  serviceName: qbittorrent
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
      - name: config
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:qbittorrent
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      - name: downloads
        persistentVolumeClaim:
          claimName: qbittorrent
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:14.3.6.99202107050919-7388-ede42910dubuntu20.04.1-ls143
        # image: alpine
        # command: ["sleep"]
        # args: ["10000000"]
        volumeMounts:
        - name: config
          subPath: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads/qbittorrent
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        - name: WEBUI_PORT
          value: '8080'
        ports:
        - containerPort: 8080
          name: qbt-webui
        - containerPort: 6881
          name: qbt-bt-tcp
          protocol: TCP
        - containerPort: 6881
          name: qbt-bt-udp
          protocol: UDP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
