# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pms-restart
spec:
  concurrencyPolicy: Forbid
  timeZone: America/New_York
  schedule: '33 4 * * *' # Restart Plex every day at 4:33am NY time
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: pms-restart
          restartPolicy: Never
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
            - bash
            - -c
            - >-
              kubectl rollout restart deployment/pms && kubectl rollout status deployment/pms
