---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-media
  namespace: default
  labels:
    name: default-media
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.114
    path: "/mnt/etank/media"
  mountOptions: &nfsMountOptions
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
    - _netdev
    - nofail
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-scratch
  namespace: default
  labels:
    name: default-scratch
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.149
    path: "/mnt/etank/scratch"
  mountOptions: *nfsMountOptions
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
  namespace: media
  labels:
    name: media
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.114
    path: "/mnt/etank/media"
  mountOptions: *nfsMountOptions
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scratch
  namespace: media
  labels:
    name: scratch
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.149
    path: "/mnt/etank/scratch"
  mountOptions: *nfsMountOptions
