---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-scratch
  labels:
    name: default-scratch
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.149
    path: "/mnt/etank/scratch"
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
    - _netdev
    - nofail
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scratch
  labels:
    name: scratch
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.149
    path: "/mnt/etank/scratch"
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
    - _netdev
    - nofail
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
  labels:
    name: logs
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.149
    path: "/mnt/etank/logs"
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
    - _netdev
    - nofail
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-ro
  labels:
    name: logs-ro
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.222.149
    path: "/mnt/etank/logs"
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
    - _netdev
    - nofail
---
 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: media
   namespace: media
   labels:
     name: media
 spec:
   capacity:
     storage: 1Pi
   accessModes:
     - ReadWriteMany
   nfs:
     server: 192.168.222.114
     path: "/mnt/etank/media"
   mountOptions:
     - nfsvers=4.1
     - rsize=1048576
     - wsize=1048576
     - hard
     - timeo=600
     - retrans=2
     - noresvport
     - _netdev
     - nofail
