# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/onepassword.com/onepassworditem_v1.json
# Velero S3 credentials for DigitalOcean Spaces
# Creates a K8s Secret with keys: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: credentials-velero
  namespace: velero
spec:
  itemPath: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/tcarhiff3b4muuwuvhnjzbzh34"
