# Hourly FSB backup of the palworld namespace
# Retains the last 24 hourly backups
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: palworld-hourly
  namespace: velero
spec:
  schedule: "0 * * * *"
  template:
    name: palworld-hourly
    includedNamespaces:
    - palworld
    storageLocation: default
    ttl: 24h
    includeClusterResources: false
    orphansInclude:
      resources:
      - persistentvolumeclaim
  paused: false
