# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/velero.io/schedule_v1.json
# Every 10-minute backup of the palworld namespace
# savegames PVC: CSI/ZFS snapshot via democratic-csi NFS driver
# config PVC: excluded (manifests only)
# Retains the last 144 backups (24h)
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: palworld-10min
  namespace: velero
spec:
  schedule: "*/10 * * * *"
  template:
    includedNamespaces:
    - palworld
    storageLocation: default
    ttl: 24h
    includeClusterResources: false
  paused: false
