apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-media
  namespace: default
  labels:
    name: default-media
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.114
    path: "/mnt/etank/media"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-scratch
  namespace: default
  labels:
    name: default-scratch
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-roms
  namespace: default
  labels:
    name: default-roms
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch/roms"
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-qbittorrent
  namespace: media
  labels:
    name: media-qbittorrent
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.220.149
    path: "/mnt/etank/scratch/downloads/qbittorrent"
  mountOptions:
    - nfsvers=4.1
