apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        # IMAGE=ghcr.io/linuxserver/jackett; skopeo --override-os linux list-tags "docker://${IMAGE}" | jq -r '.Tags[]' | sort -V | tail -n1
        image: ghcr.io/linuxserver/jackett:version-v0.24.1567
        # image: alpine
        # command: [ "sleep" ]
        # args: [ "infinity" ]
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/New_York"
        ports:
        - name: http
          containerPort: 9117
        livenessProbe:
          httpGet:
            port: http
            path: /health
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
