---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
