# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolume-v1.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-jackett
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:jackett
    lun: 1
    fsType: ext4
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  volumeName: config-jackett
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
