repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ["--allow-multiple-documents"]
    exclude: ^bootstrap/apps\.yaml$|^bootstrap/apps-helm\.yaml$
  - id: check-added-large-files
- repo: https://github.com/google/yamlfmt
  rev: v0.21.0
  hooks:
  - id: yamlfmt
- repo: https://github.com/nlopez/check-yamlschema
  rev: v0.0.7-fix
  hooks:
  - id: check-yamlschema
    exclude: ^bootstrap/apps\.yaml$|^bootstrap/apps-helm\.yaml$
