---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
---
apiVersion: v1
kind: Namespace
metadata:
  name: mon
  labels:
    name: mon
---
apiVersion: v1
kind: Namespace
metadata:
  name: jobs
  labels:
    name: jobs
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux
  labels:
    name: flux
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: pgo
  labels:
    name: pgo
