---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: "instance-64514"
    localASN: 64514
    peers:
    - name: "peer-64513-gw"
      peerASN: 64513
      peerAddress: 192.168.222.1
      peerConfigRef:
        name: "cilium-peer"

---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: my-lb-pool
spec:
  blocks:
    - cidr: "10.0.10.0/24"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 120
