---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
controlPlaneEndpoint: "192.168.222.245:6443"
networking:
  podSubnet: "10.43.16.0/20"
  serviceSubnet: "10.43.32.0/20"
apiServer:
  extraArgs:
    - name: "enable-admission-plugins"
      value: "NodeRestriction,MutatingAdmissionPolicy"
    - name: "runtime-config"
      value: "admissionregistration.k8s.io/v1alpha1=true"
    - name: "feature-gates"
      value: "kube:MutatingAdmissionPolicy=true"
    - name: "bind-address"
      value: "0.0.0.0"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
waitForAllControlPlaneComponents: true
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
proxy:
  disabled: true # disable kube-proxy
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
