---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
controlPlaneEndpoint: "192.168.222.245:8443"
networking:
  podSubnet: "10.43.16.0/20"
  serviceSubnet: "10.43.32.0/20"
etcd:
  local:
    serverCertSANs:
      - "192.168.222.245"
    peerCertSANs:
      - "192.168.222.245"
apiServer:
  certSANs:
    - "192.168.222.245"
  extraArgs:
    - name: "enable-admission-plugins"
      value: "NodeRestriction,MutatingAdmissionPolicy"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
waitForAllControlPlaneComponents: true
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
proxy:
  disabled: true # disable kube-proxy
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
