apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  namespace: default
  labels:
    name: nextcloud-data
  annotations:
    volume.beta.kubernetes.io/mount-options: "nfsvers=4.1"
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.222.114
    path: "/mnt/etank/nextcloud"
