apiVersion: batch/v1
kind: CronJob
metadata:
  name: cfwarp-heartbeat
  namespace: media
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            args:
            - "-c"
            - "curl -m 5 -v --socks5-hostname cfwarp.default.svc.cluster.local:1080 https://cloudflare.com/cdn-cgi/trace"
          restartPolicy: OnFailure
