---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namspace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namspace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namspace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:v0.7.1
          args:
            - --source=ingress
            - --domain-filter=desertbluffs.com
            - --provider=aws
            - --registry=txt
            - --txt-owner-id=ZWD12EEM7603F
            - --txt-prefix=nz07-

          envFrom:
            - secretRef:
                name: external-dns
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBtUX2DVMG9J/MV5sr8B0lAu5WYw8jy9w3pXcJx5EsvQBRk6U8R+cYQTVQZF/6lQzjZqqkHy4P5Qq7cluPGfBWdQxVA0hSuFruXuJteWv/Di8HLG85t8hMNZH0HqsXro5nezmRXnOx1nyPBAqNzw/6mof5EMm4mQ37huwMp2KvUs4beqtuxvFytAUjdbhDTtL5kiVG0lsIlvnspKQW3htt2NnxxGuBb+IcAaEJCPePD7/nAFVrfVPAovVUooLgj+vxYJB4goPsoGE9009FHW5YeubYd0K/9m/MmBxg9XjUMnhVnxkdi4sFSznKZipVMT9EWnfxLedC51W/h1tzkdzByBwdczVCCZw7fblE2TUiwneN1NSUr1LehKhkRXlGASAuE/01LXU5rgUu/9m7ThlNphVmOdgWqP2RKkoSgOaslMr4GMlVBFb25GMU5pJiY3MDe/A797H+mws57du4HQlvxlbvvbvL2RRSCbrdNQXg3bQzk7z2DxhCXnQiL+EgKE49ihMQBI9/Ms8Y3VdW1Ase1ARn+gkH6xL2VRRQqKJdrNqdJMB6hyi76E0cKXtO7CM1hp8KLp5trJckoY8Lj+5g6pa+sVO+yG3otfl0XNYT2jX97p+X2Bhk198L8k+1oYx/3LBQ0s+pbEs+hmQwKqH6n9BuqxELU5JmiiOLQUe8eDwijNax6xzjaxOgizUa73PaHIPKyB12TYLZ3hkzW1EN5QhKbag==
    AWS_SECRET_ACCESS_KEY: AgBQ/GvQK26nnEx9e9dqQzQcsKZBQrXlmWaxRggwSs2sDqUM9+strGY63RRDuJj6v8YbijWRWsqhwWZtLrK0PK2RS4PPAv1gE98SVJktKTYtVe/Gxw03ptt9Hj0bbC2M7mW/Uou7PgqhdYyDyN7xdIMQwZjQpX+kDI7iAhwGtMxl1yRbFX6pivrZchsVvPraoYnCKJ9vvAiFWljBMtS0eRdpQ7zZhrkfz06zA89wHf8rq2Q+fAHjpIHs3w5TP1bfkKQ/b36TbuuVW5Bu1BT6huygB/xEZlk4uFZEm0Do4MXz8wXhBpnfwN2RcNMBim4dxgQY2enLISYzw+mmc7uxdGA/Es8lUSeRevH5u6cjWbRZpgYwQ/XX0O8sd7bGN/bv/xlqHJ4x6JXfuJTtv8fJGJ3oCFhIGtbU8jbdmSnitRDfJELYZdYlLRFmzNnl+C02x1B1mqPMP7Qg800c8wNHj1D0ji4dsuv/jed6nwYJp8BkbGPFPj0e0XpTPjt8DSKhI61cFjQvw81zK8dRvel+270Y+rrOCFap72cpF4bUk67pfPme20R2KnoG9zCyGIiAzJK93P6jeLi7ejJJTJkJN0diTLgMwA3C7eDX9NpT79dCyFFZZEdGvN1g/+oEo4nH/6eM2gpTICXCl05kzRaq3dDsoRGcyEo1mRoIU/O9kxoEVyQ1e5CsasRq3yH9ZlWsLYpOnly+B6Hw6IfPQGBMRuYL7W4fYcJBMFDs3IZyUR6bIgx7+5gg97cA
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: default
