---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namspace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namspace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namspace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
  - kind: ServiceAccount
    name: external-dns
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namspace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: registry.opensource.zalan.do/teapot/external-dns:v0.7.1
          args:
            - --source=ingress
            - --domain-filter=desertbluffs.com
            - --provider=aws
            - --registry=txt
            - --txt-owner-id=ZWD12EEM7603F
            - --txt-prefix=nz07-

          envFrom:
            - secretRef:
                name: external-dns
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: external-dns
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAG/erYNfKXhej/ObTCckj0g/wugN+o4YNSyGXxx71MfH21JDY182Wo8K9MuAPb/OTxELtUU5h22M7HJv8i9ZU0DqxTsb+illvmplbKpaUed8ekDBeLLuBUKsNT3ejoIsyGdVRVIEcLBNlRU1EQqKw/k2Vm/83a7MGdoTu1KZbPqhv41YB6iJ8xK9Gi+Qucxaxvug466+dzTmDw3w6NeswuEqNNPOvbALwv+4gSbJ6cOENVF+QSgx86+Qk3O+2P77UOTBGM5vcpjOKcDZIwo0sZj+Q+opu3HsqwV6HWBT2RIuz18lAuT1ChiUQTOJFVvbQCk4FpmbiHwCmgseL3tER+EAG/WJ62N/x2vyj4cb1g5HFuQXBEcJ4MCWW3bIhyPYJNPbLh3LepiYyUkrrhYY/QB1irSVwXzLJZ7RaiBz8dXTiL1tdcnQT2G/SYQczYpMYRA5Eu4r58ppbmt1Xb89tvHte/MRlRVhngW77ROmzS/eVWBHqIdjfVFwx1tdT7JIVCPfp7Z7qK4r6C/S+bMqNuQTDK3N17U4TYW+AhE/KzYyfXcvjzo9DJf7JVyYxZNg9mAL0zZIIYvfcCvVNCH8TwCyFz4AtDwaH1L/aBEdCgO7BCQW0osP+PMj7yjie/+fD+R26UffZ1GdpGekZ0Mav8XzQmhfDqmrZzNPmeIEtnqL9rYMOeVRoj3wmYJ4tIwoo2Wla+0WdSZHA3awXbOdTpliY5zw==
    AWS_SECRET_ACCESS_KEY: AgBkeys8LQgd17knj6RF/0KigTZ6bXBKglFpWoX0RjIXIFLXgWfov1uE4pNm+jKfaD1nMXFugrNFUvOGDnHKNGposZHLwinnTFOYXUmgMpqll35o6C213gh5/uYhzsu/mYNbyP9OjclMIu4XfFtg0g2zTXtswtoHkzfAWZw5+2CRJ2K9+B5SwZ0U6XLVDWzCvYs4DBffRM4Abjzk5wH8SLOYMvbYT7h6IiRMibz4n84Gukcbmdr8HQQAxYnzc05aNmGEPn4o5ybVaHPtdJ503CBDdjWKxGZeb7eo4BQie37wtWYQ6RlKWjyr7VqjSJLY/urpej0+iX9ARbUxH5bqTQ8BS6kF8eseEaaXDpY7pH+iQIcx9B/6f8NRtBbhUXzolBNQfRHJhI5v327/V2QltfyAy7YeBYVvdZuYSKOet4f5ffa+9X7crmqOI52XK63f2N+DVuCf4Xw+J1k/N3camyNTrBAxo6AKWzjCgA92/LYbcOlFS3PrODn9l+U8JKyF5mJOhfuQXL/X2Q7dEsK1GNIXs26kLQsQRiMJpeyh3UZN52PdN4C/VSAx1Upop+6QSeEdG61zi/S/MSDhPFM7zWyOqYMZiD0dwRwhRNvMhwD5WGI7KVVA0q5DtMYvuc82IXXWDozX5q/L8ZXMyImUrFzCSY0034R7moCKDYfrqY6jq1oX7yFSltPrl19jbf1f8DANidVDQIbFic2/HYtyjSOLJ+qlNIjoofFTIvhOnUtZF7cpJ/EGuY8M
