# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: palworld-modded-secrets
  namespace: palworld-modded
spec:
  itemPath: vaults/evjh25ux2mnoufaut6qhvm2pdi/items/hru6xhywqkuevbknqvp6plcgby
