configs:
  params:
    server.insecure: "true"
controller:
  extraArgs:
  - --enable-new-git-file-globbing # https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git-File-Globbing/
