---
global:
  domain: argocd.macaroni-pirate-ts.net

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: tailscale
    annotations:
      tailscale.com/proxy-group: ingress-proxies
      tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
      tailscale.com/hostname: argocd
    tls: false
    extraRules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: '{{ include "argo-cd.server.fullname" . }}'
              port:
                name: '{{ .Values.server.service.servicePortHttpName }}'
    extraTls:
    - hosts:
      - argocd
  httproute:
    # -- Enable HTTPRoute resource for Argo CD server (Gateway API)
    enabled: true
    # -- Additional HTTPRoute labels
    labels: {}
    # -- Additional HTTPRoute annotations
    annotations:
      external-dns.alpha.kubernetes.io/hostname: c.desertbluffs.com,argocd.desertbluffs.com
    # -- Gateway API parentRefs for the HTTPRoute
    ## Must reference an existing Gateway
    # @default -- `[]` (See [values.yaml])
    parentRefs:
    - name: internet
      namespace: envoy-gateway-system
      group: gateway.networking.k8s.io
      kind: Gateway
    hostnames:
    - c.desertbluffs.com
    - argocd.desertbluffs.com
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
