apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deluge
  namespace: media
spec:
  encryptedData:
    auth: AgCZA0FysVN3Z1ehM9dEddY39vB0KeIjrQ4eP/bCUlM1ixPFiNVYhs9sMGbn5CaBEuS8Bv6JhvMxNwbA9JDJ8mmKS/z6b1mcGJ9HWGrEEGqRtH9VkabrxH8bJS7Fh9it5uIb/NbRXI0txG/QvWRI9+hAprdHXSDu9PEPjkMjo9EX8C6mCit69B6Wu4eOFGkda+t8Svw34gkiAwwYbL8TvCv08zwT9WHFSIDUaUF8h6kg44VwtRJy2JLsiWojtvhSzFZo1y5QVj0CdTwYW0by1rWaSxQw+H4BV+mSvJYX0ILDkaYOsdPvoci2UInS4gH9pK5s0IIn94hVZSJJxMpeowiBMEyswJWSspQxavp/UG/GfLafnBVOfswtIQe3AbNufK0CRcvFkgRwKEBWjsBb4Emnu5yu8P3d+gtnIVvD65+yz9n5AYmkc44xKecuLwRQ4mPzxPed3TEQ8d8ovaXY53BoX25r5IUqAeC+QdNdYFevZJLrMkmiJE4BVAkxJEJnQVy44Mfql7GqnlpEXN/My2IRUA34nyEXBkMOzSnKor16FhAob/nAZpN6tSZ5pCawblKMKA+i63lsbqOa+j0WLluKPVxI/YDOEhdSfJFcqqFzoiMHcDppTrLEbariaILVhGVUxLjJAQNYEd+YCexqizV7pYuoQEg1nUjaKuNrSKMhw4KEl86ZXupEYJqChRVAEB0FV3SmMDW0HDBL+C9FihFPw/sk3ulVILCd5Y7BF6CugA7iGH1BxlskEhuj1mYvRsjs/p4KsIYcVTHz1cCxqYSN2fIu9Yxcjo4eHzZAMswvyA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: deluge
      namespace: media

