---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-iscsi-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:heimdall
    lun: 1
    fsType: ext4
  mountOptions:
    - noatime
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: heimdall-iscsi-pvc
    namespace: media
