---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-iscsi-pvc
  namespace: media
spec:
  volumeName: heimdall-iscsi-pv
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
