---
apiVersion: v1
kind: Service
metadata:
  name: heimdall
  namespace: media
spec:
  selector:
    app: heimdall
    version: v1
  ports:
    - name: heimdall-http
      port: 80
    - name: heimdall-https
      port: 443
