---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: heimdall
  namespace: media
spec:
  serviceName: heimdall
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
      - name: config
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:heimdall
          targetPortal: 192.168.222.149
          lun: 1
          fsType: ext4
      containers:
      - name: heimdall
        image: lscr.io/linuxserver/heimdall:version-v2.4.13
        volumeMounts:
        - name: config
          mountPath: /config
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - containerPort: 80
          name: heimdall-http
        - containerPort: 443
          name: heimdall-https
