---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: invidious
  namespace: media
  annotations:
    fluxcd.io/automated: 'false'
spec:
  serviceName: invidious
  replicas: 1
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      volumes:
      - name: postgresql
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:invidious-postgresql
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      - name: invidious-config
        secret:
          secretName: invidious-config
      containers:
      - name: invidious
        image: nlopez/invidious@sha256:46cc5e5c0e65bc62a6bb7c6968e1ee5c12a898469c46eb58b987cb03c194fcf2
        # command: ["sleep"]
        # args: ["10000000"]
        ports:
        - containerPort: 3000
          name: invidious
        volumeMounts:
        - name: invidious-config
          mountPath: /invidious/config/config.yml
          subPath: config.yml
          readOnly: true
      - name: postgresql
        image: postgres:10
        volumeMounts:
        - name: postgresql
          mountPath: /var/lib/postgresql/data
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          value: invidious
        - name: POSTGRES_USER
          value: kemal
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: invidious-postgresql
              key: POSTGRES_PASSWORD
