---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freenas
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
    nginx.ingress.kubernetes.io/auth-tls-secret: "ingress-nginx/auth-tls-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "required"
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - q.desertbluffs.com
  rules:
    - host: q.desertbluffs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas1
                port:
                  number: 443
