apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-nas1-mtank
spec:
  storageClassName: nas1-mtank-iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
