---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydra2-iscsi-pvc
  namespace: media
spec:
  volumeName: hydra2-iscsi-pv
  resources:
    requests:
      storage: 2G
  accessModes:
    - ReadWriteOnce
