---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hydra2
  namespace: media
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.hydra2: 'regex:^v2\.[0-9\.]+-ls[0-9]+$'
spec:
  serviceName: hydra2
  replicas: 1
  selector:
    matchLabels:
      app: hydra2
  template:
    metadata:
      labels:
        app: hydra2
    spec:
      volumes:
      - name: hydra2-config
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:hydra2
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      containers:
      - name: hydra2
        image: linuxserver/nzbhydra2:v2.28.0-ls16
        volumeMounts:
        - name: hydra2-config
          subPath: config
          mountPath: /config
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - containerPort: 5076
          name: hydra2
        readinessProbe:
          tcpSocket:
            port: hydra2
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: hydra2
          initialDelaySeconds: 15
          periodSeconds: 20
