apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
spec:
  defaultBackend:
    service:
      name: argocd-server
      port:
        name: https
  tls:
    hosts:
    - argocd
  ingressClassName: tailscale
