# GitHub Actions Runner Controller (ARC) — controller values (unstable)
replicaCount: 1
flags:
  logLevel: "info"
leaderElection:
  enabled: true
metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"
