---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: icloudpd-init-ondemand
spec:
  # Dummy schedule - this cronjob is only triggered manually
  schedule: "0 0 31 2 *" # Never runs (Feb 31st doesn't exist)
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: init
            # IMAGE=boredazfcuk/icloudpd; skopeo --override-os linux list-tags "docker://${IMAGE}" | jq -r '.Tags[]' | grep '^[0-9]' | sort -V | tail -n1
            image: boredazfcuk/icloudpd:1.0.1329_22-02-2026
            env:
            - name: TZ
              value: "America/New_York"

            volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /home/user/iCloud

          volumes:
          - name: config
            persistentVolumeClaim:
              claimName: config
          - name: media
            persistentVolumeClaim:
              claimName: media

          restartPolicy: Never
