apiVersion: apps/v1
kind: Deployment
metadata:
  name: icloudpd
  labels:
    app: icloudpd
    version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: icloudpd
      version: v1
  template:
    metadata:
      labels:
        app: icloudpd
        version: v1
    spec:
      serviceAccountName: default
      containers:
      - name: icloudpd
        # IMAGE=boredazfcuk/icloudpd; skopeo --override-os linux list-tags "docker://${IMAGE}" | jq -r '.Tags[]' | grep '^[0-9]' | sort -V | tail -n1
        image: boredazfcuk/icloudpd:1.0.1368_04-05-2026
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/New_York"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /home/user/iCloud
          subPath: icloud
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: media
        persistentVolumeClaim:
          claimName: media
