# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolumeclaim-v1.json
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
spec:
  volumeName: media-icloudpd
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-icloudpd
  labels:
    name: media-icloudpd
spec:
  capacity:
    storage: 1Pi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.222.114
    path: "/mnt/etank/media"
  mountOptions:
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
  - _netdev
  - nofail
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
