apiVersion: apps/v1
kind: Deployment
metadata:
  name: ytpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ytpot
  template:
    metadata:
      labels:
        app: ytpot
    spec:
      containers:
      - name: ytpot
        image: docker.io/brainicism/bgutil-ytdlp-pot-provider:1.3.1@sha256:1fd724c0a987a1eaa7e0875667a55770f954d8634fdbba96d858072f4a655afe
