---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
      version: v1
  template:
    metadata:
      labels:
        app: toolbox
        version: v1
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      # nodeName: knode2
      serviceAccountName: toolbox
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: config
          configMap:
            name: toolbox
        - name: yt-dlp
          configMap:
            name: yt-dlp
            items:
              - key: config
                path: config
        - name: temp
          emptyDir: {}
      containers:
        - name: toolbox
          image: docker.io/nlopez/media-toolbox:latest
          imagePullPolicy: Always
          resources:
            requests: {}
            limits: {}
          command: ["sleep"]
          args:
            - infinity
          volumeMounts:
            - name: media
              mountPath: /media
            - name: scratch
              mountPath: /scratch
            - name: yt-dlp
              mountPath: /home/user/.config/yt-dlp/config
              subPath: config
            - name: temp
              mountPath: /yt-dlp-temp
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: HISTFILE
              value: /media/youtube/cfg/bash_history
            - name: HISTFILESIZE
              value: ""
            - name: HISTSIZE
              value: ""
            - name: PROMPT_COMMAND
              value: "history -a"
            - name: TZ
              value: "America/New_York"
            - name: HISTTIMEFORMAT
              value: "%Y-%m-%dT%H:%M:%S%z "
