---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: toolbox
  namespace: media
spec:
  serviceName: toolbox
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
      version: v1
  template:
    metadata:
      labels:
        app: toolbox
        version: v1
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      nodeName: knode2
      serviceAccountName: toolbox
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: config
          configMap:
            name: toolbox
        - name: yt-dlp
          configMap:
            name: yt-dlp
            items:
              - key: config
                path: config
      containers:
        - name: toolbox
          image: docker.io/nlopez/media-toolbox:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits: {}
          command: ["sleep"]
          args:
          - infinity
          volumeMounts:
            - name: media
              mountPath: /media
            - name: scratch
              mountPath: /scratch
            - name: yt-dlp
              mountPath: /home/user/.config/yt-dlp/config
              subPath: config
          securityContext:
            allowPrivilegeEscalation: false
