## Spegel P2P image distribution for Kubernetes
## https://github.com/spegel-org/spegel
image:
  repository: ghcr.io/spegel-org/spegel
  tag: v0.7.3
commonLabels:
  tags.datadoghq.com/env: homelab
  tags.datadoghq.com/service: spegel
  tags.datadoghq.com/version: v1
