apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tautulli
  namespace: media
spec:
  encryptedData:
    TAUTULLI_API_KEY: AgBQXwQm1Qbf1FYWC2E6mbPWvGEElQlpdyu0py0WtuHWYwu8wLsvh/7QErWDeOUxaF3h7QBSQ+qREbgEMXoG+0XUXuR2oHXVZoywDuJUekD10flZyRHk3OqW75Ucq83pjryjlRYMue9GGKSr4e4XaePjxqKwYmZ2K3gievP/TI3M5AdZQsOJqjvLZLvjMdowI3LhMAh3Cpu7ku+dy/Qj8YdCDOEqkZgxYCV98bsAt1S5k6iY8ipdSQ5nZPBdn6ramznEqqu24BMVnRwXzNiEvl6vYXeVllEFBfgOuLlSkh49b5dCUhdEc/+rZtlNL50We7HUug45dJWdJcLlfKmX92zovzvJdUUWqEXfEhEQQK4mcUZsKVTFEMJGANnhZz2Q8r1n3cdD1YkFyqnbJDSZyS8SXUSulOTjUFavO1nxbUzz5XvA29WlAINMxDBlx2jAgkVOHNOgfxUwvhUnkjuxJrbiidGb0pUHi8WvYZjgwwoh/ZNfYlii75Z6n3O8YOHosTHsiJ1KCjsU1yc6PPeZqJ5xLGMz6nd288+A/DaivNZAEqFu1csh3PCUILQyDmU2tAbckTLL/XEPUwIUl+qnko7+OJJ5bCW2QTWf1phBmp14YOkT6JiUVF7XL76bYvXwwUmkIjhLv6hjDvhUxXBid+QZ+CZ8pjIKNrhHNCMm+yYGVgu3GtQQRTQUz48U9crRfi/v3BwJFbhzSioDixMphXRncramrqf8KbDRfEE47u1ECg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: tautulli
      namespace: media
