apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tautulli
  namespace: media
spec:
  encryptedData:
    TAUTULLI_API_KEY: AgA+9dSHNuf8v6XKWQCjR/kz8d/ys92SR4wBmUStkCkEMWJX1cnmgG6TZBsJkmSXXNYl6cMD+VYSCFHDMSQg8MUrQ29i9Xz3F/1xvdij+Jh2f7xvV2OHcBSmf3JQflwa8mTcIehKg1pFJUZ8UAGP9Erc7HPy+mXZNkAd4UjbdqW5/MppgS9YDQwBzvGwEKS6nHYBhah5d+q4a9+wf+959UNBYROPuc0+Uc0MVw1345Bo4AUfGzb/PogBQbidIAHeeCaVixPumpArzvYdnIGpsCdVQ0IYIjN2uDIHKPXtT/SFkWBoSsl6qRQPc5MXxXAumqbg9zX2n9VwgrMWLa9fnPM96MV4QF7sBiiwA6P0pv3DzzcxAEfDLg2TJEFH3Nl3gk8KFkqwmgCikN70nvy3AFWp6BBvrG/GpXQOjgeOsV8DQR7RhIMPSQUue2pQY5s34yxgg15Y9eb0gvnfOMcGH33tMdXihD9h1Dh3lpoqnALfQ4DRjUzpmdiygL5cUaxvptD0umtHtRLM/Ck9RVTMgrklslXd4/wsOYOVJvNRiDgdTOnWbqlkAidKQ0kuO/1GDPuvBTm0wvvEb9my2AsFYGcuiot4KN1dTgZguPdIoF9zZcAoT0sb5YM/5NwQbXz8VmEi0vi7BiA2hCYeFnTCfMa6EiuO7nF8Qol8T5N+i2zU+WsfsMjuYmt1Ky/h6P+xDIyCuxD27C56S+QzHEmsaO+Aehe4GllE5H2WK0iq3HVWWQ==
  template:
    metadata:
      creationTimestamp: null
      name: tautulli
      namespace: media
