apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: media
  labels:
    app: tautulli
    version: v1
spec:
  selector:
    app: tautulli
    version: v1
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
