apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
  namespace: media
  labels:
    app: tautulli
    version: v1
spec:
  serviceName: tautulli
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
      version: v1
  template:
    metadata:
      labels:
        app: tautulli
        version: v1
    spec:
      # nodeName: knode1
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      volumes:
      - name: tautulli-iscsi-ssd
        persistentVolumeClaim:
          claimName: tautulli-iscsi-pvc-ssd
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      containers:
      - name: tautulli
        # IMAGE=lscr.io/linuxserver/tautulli; echo -en "$IMAGE:$(crane ls $IMAGE | sort -V | tail -n1)" | pbcopy
        image: lscr.io/linuxserver/tautulli:version-v2.14.4
        # image: alpine
        # command: ["sleep"]
        # args: ["infinity"]

        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            memory: "512Mi"

        volumeMounts:
        - name: tautulli-iscsi-ssd
          mountPath: /config
        - name: logs
          mountPath: /logs-pms
          subPath: pms
          readOnly: true

        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/New_York"

        ports:
        - name: http
          containerPort: 8181

        livenessProbe:
          httpGet:
            path: /status
            port: http
          periodSeconds: 15
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6

        readinessProbe:
          httpGet:
            path: /status
            port: http
          periodSeconds: 15
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
