---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tautulli
  namespace: media
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.tautulli: 'regex:^v2\.[0-9\.]+-ls[0-9]+$'
spec:
  serviceName: tautulli
  replicas: 1
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      volumes:
      - name: tautulli
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:tautulli
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext2
      containers:
      - name: tautulli
        image: linuxserver/tautulli:v2.6.3-ls17
        volumeMounts:
        - name: tautulli
          subPath: config
          mountPath: /config
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: tautulli
          containerPort: 8181
        readinessProbe:
          tcpSocket:
            port: tautulli
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: tautulli
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: tautulli-exporter
        image: tubaguy50035/tautulli_exporter:v0.1.0
        ports:
        - name: exporter
          containerPort: 9487
        env:
        - name: TAUTULLI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tautulli
              key: TAUTULLI_API_KEY
        - name: TAUTULLI_URI
          value: 'http://127.0.0.1:8181'
