---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: example
spec:
  endpoints:
    - dnsName: example.kamotimestamps.com
      targets:
        - example.com
      recordType: CNAME
