# +argocd:skip-file-rendering
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- pv.yaml
- pvc.yaml
- pvc-test-nas1-mtank.yaml
configMapGenerator:
- files:
  - yt-dlp.conf
  name: toolbox-config
