# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolumeclaim-v1.json
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
spec:
  volumeName: media
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Pi
