--audio-multistreams
--video-multistreams
--format-sort "fps,res,vcodec:vp9"
--format "(bv*+ba[acodec=opus]+ba[acodec^=mp4a]/bv*+ba/b)[format_id!*=-drc]"
--merge-output-format mkv
--remux-video mkv
--extractor-args "youtube:player-client=mweb"
--proxy "socks5://cfwarp.default.svc.cluster.local:1080"

--output "%(channel,uploader)s_[%(channel_id)s]/%(release_timestamp>%Y,timestamp>%Y)s/%(release_timestamp>%m,timestamp>%m)s/%(release_timestamp>%Y-%m-%d--%H-%M,timestamp>%Y-%m-%d--%H-%M)s_%(title)s_[%(id)s].%(ext)s"
--paths "temp:/yt-dlp-temp"
--paths /media/youtube/out
--restrict-filenames
--clean-info-json
--no-mtime

--add-header "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36 Edg/135.0.0.0"
--cache-dir /media/youtube/cache
--no-cookies
--no-part
--verbose

--alias audio      "-f ba --no-write-playlist-metafiles --extract-audio --write-thumbnail --convert-thumbnails 'webp>png' --write-info-json --embed-metadata --parse-metadata '%(release_timestamp>%Y%-m-%d,timestamp>%Y-%m-%d)s:%(meta_date)s' --parse-metadata ' ASMR: %(meta_genre)s' --parse-metadata '%(uploader)s:%(meta_artist)s' --parse-metadata '%(meta_artist)s:%(meta_album_artist)s' --parse-metadata '%(title)s:%(meta_album)s' --parse-metadata '%(webpage_url)s:%(meta_comment)s'"
--alias opus       "--format 'ba[acodec=opus][format_id!*=-drc]' --extract-audio --download-archive /media/youtube/cfg/download-archive/opus.txt"
--alias aac        "--format 'ba[acodec^=mp4a][format_id!*=-drc]' --extract-audio --download-archive /media/youtube/cfg/download-archive/aac.txt"

--alias autosubs   "--write-subs --write-auto-subs --sub-lang en --no-download --download-archive /media/youtube/cfg/download-archive/autosubs.txt"
--alias livechat   "--live --write-subs --sub-lang live_chat --no-download --download-archive /media/youtube/cfg/download-archive/livechat.txt"

--alias comments   "--write-comments --write-info-json --no-download"
--alias thumbnail  "--write-thumbnail --convert-thumbnails 'webp>png' --no-download"

--alias metadata   "--write-thumbnail --convert-thumbnails 'webp>png' --write-info-json --embed-chapters --embed-metadata --embed-info-json --embed-thumbnail"
--alias video      "--metadata --write-subs --write-auto-subs --write-comments --download-archive /media/youtube/cfg/download-archive/default.txt"

--alias live       "--live-from-start --wait-for-video 60"
--alias livestream "--live --metadata --download-archive /media/youtube/cfg/download-archive/default.txt"

--alias force      "--force-overwrites --no-download-archive"
