apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-tailscale
  namespace: media
spec:
  tls:
  - hosts:
    - wretched-degree
  defaultBackend:
    service:
      name: radarr
      port:
        name: http
  ingressClassName: tailscale
