---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: media
spec:
  serviceName: radarr
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        rclone-mounts: "true"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pms
              topologyKey: "kubernetes.io/hostname"

      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:version-5.0.3.8127

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              memory: "1Gi"

          volumeMounts:
            - name: radarr
              subPath: config
              mountPath: /config
            - name: media-nfs
              mountPath: /media
            - name: scratch
              mountPath: /downloads
              subPath: downloads

          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"

          ports:
            - name: http
              containerPort: 7878

          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - test -f /media/.anchors/dropbox
          #   periodSeconds: 10
          #   failureThreshold: 3

          startupProbe:
            httpGet:
              port: http
              path: /
            periodSeconds: 10
            failureThreshold: 30

      volumes:
        - name: radarr
          persistentVolumeClaim:
            claimName: radarr-iscsi-pvc
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
        - name: media-nfs
          persistentVolumeClaim:
            claimName: media
