---
# PostgreSQL database volume using iSCSI
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-database-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:immich-database
    lun: 0
    fsType: ext4
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
---
# PostgreSQL cluster for Immich using cloudnative-pg
# Reference: https://github.com/immich-app/immich-charts#prerequisites
# https://github.com/immich-app/immich-charts/blob/main/local/cloudnative-pg.yaml

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 1
  postgresql:
    shared_preload_libraries:
    - 'vchord.so'
  storage:
    size: 20Gi
    pvcTemplate:
      accessModes:
      - ReadWriteOnce
      storageClassName: ""
      resources:
        requests:
          storage: 20Gi
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: onepassword-immich-database
      postInitApplicationSQL:
      # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
      - CREATE EXTENSION vchord CASCADE;
      - CREATE EXTENSION earthdistance CASCADE;
