---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-custom
  namespace: ingress-nginx
data:
  custom.yaml: |
    ---
    server:
      host: 0.0.0.0
      port: 9091
      buffers:
        read: 32768
        write: 4096
    access_control:
      default_policy: deny
      rules:
        - domain:
            - "*.desertbluffs.com"
          policy: one_factor
    authentication_backend:
      password_reset:
        disable: true
      file:
        path: /config/users.yaml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 1024
    storage:
      local:
        path: /tmp/authelia.sqlite3
    session:
      name: authelia_session
      expiration: 1h
      inactivity: 5m
      remember_me_duration:  1M  # 1 month
      domain: desertbluffs.com
    notifier:
      disable_startup_check: true
      filesystem:
        filename: /dev/null
