---
kind: Service
apiVersion: v1
metadata:
  name: sabnzbd
  namespace: media
spec:
  type: ExternalName
  externalName: 192.168.222.10.sslip.io
  ports:
    - name: http
      port: 80
      targetPort: 8080
