---
kind: Service
apiVersion: v1
metadata:
  name: sabnzbd
  namespace: media
  labels:
    tailscale.com/proxy-class: "prod"
  annotations:
    tailscale.com/hostname: "dead-room"
    tailscale.com/expose: "true"
spec:
  type: ExternalName
  externalName: 192.168.222.10.sslip.io
  ports:
    - name: http
      port: 80
      targetPort: 8080
