apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-tailscale
  namespace: media
spec:
  tls:
  - hosts:
    - majestic-fear
  defaultBackend:
    service:
      name: sonarr
      port:
        name: http
  ingressClassName: tailscale
