---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-iscsi-pv-ssd
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:sonarr-ssd
    lun: 1
    fsType: ext4
  mountOptions:
    - noatime
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: sonarr-iscsi-pvc-ssd
    namespace: media
