---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pv-claim
  labels:
    app: sonarr
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
