---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: media
spec:
  serviceName: sonarr
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        rclone-mounts: "true"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      nodeSelector:
        workload: download
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:version-3.0.9.1549

          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"

          ports:
            - name: sonarr
              containerPort: 8989

          livenessProbe:
            httpGet:
              path: /
              port: sonarr
            exec:
                command:
                  - sh
                  - -c
                  - test -f /media/.anchors/dropbox
            periodSeconds: 15
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /
              port: sonarr
            exec:
              command:
                - sh
                - -c
                - test -f /media/.anchors/dropbox
            periodSeconds: 15
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6

          volumeMounts:
            - name: sonarr
              subPath: config
              mountPath: /config
            - name: media-rclone
              mountPath: /media
            - name: scratch
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: sonarr
          persistentVolumeClaim:
            claimName: sonarr-iscsi-pvc
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
