---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
    version: v1
spec:
  serviceName: sonarr
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
      version: v1
  template:
    metadata:
      labels:
        app: sonarr
        rclone-mounts: "true"
        version: v1
    spec:
      serviceAccountName: sonarr
      dnsConfig:
        options:
          - name: ndots
            value: "1"

      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:version-3.0.9.1549

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              memory: "1Gi"

          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"

          ports:
            - name: sonarr
              containerPort: 8989

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - test -f /media/.anchors/dropbox
            periodSeconds: 15
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - test -f /media/.anchors/dropbox
            periodSeconds: 15
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6

          volumeMounts:
            - name: sonarr
              subPath: config
              mountPath: /config
            - name: media-rclone
              mountPath: /media
            - name: scratch
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: sonarr
          persistentVolumeClaim:
            claimName: sonarr-iscsi-pvc
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
