provider:
  name: cloudflare
env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-api-token
      key: api-token
- name: EXTERNAL_DNS_TXT_ENCRYPT_AES_KEY
  valueFrom:
    secretKeyRef:
      name: txt-encrypt-aes-key
      key: aes_key
- name: EXTERNAL_DNS_TXT_ENCRYPT_ENABLED
  value: "true"
sources:
- service
- ingress
- gateway-httproute
- gateway-grpcroute
- gateway-tlsroute
- gateway-tcproute
- gateway-udproute
domainFilters:
- desertbluffs.com
- radoncanyon.com
extraArgs:
- --cloudflare-record-comment=managed by external-dns
- --min-ttl=1s
logLevel: debug
