provider:
  name: cloudflare
env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-api-token
      key: api-token
- name: TXT_ENCRYPT_AES_KEY
  valueFrom:
    secretKeyRef:
      name: txt-encrypt-aes-key
      key: aes_key
sources:
- service
- ingress
- gateway-httproute
- gateway-grpcroute
- gateway-tlsroute
- gateway-tcproute
- gateway-udproute
extraArgs:
- --txt-encrypt-enabled
- --txt-encrypt-aes-key=$(TXT_ENCRYPT_AES_KEY)
extraVolumes:
- name: txt-encrypt-aes-key
  secret:
    secretName: txt-encrypt-aes-key
extraVolumeMounts:
- name: txt-encrypt-aes-key
  mountPath: /etc/external-dns/txt-encrypt-aes-key
  readOnly: true
logLevel: debug
