---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -ytarchive
images:
- name: docker.io/nlopez/media-toolbox
  newTag: "d188916"
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: ytarchive
patches:
- path: patch.yaml
  target:
    kind: CronJob
    name: toolbox-cron
