# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-repo-dockerhub
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  itemPath: "vaults/copxopw5gkuo2m3cv7acvkrfxy/items/jy7ohcmdhsn5dpj3kp252vwicm"
