# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-repo-dockerhub
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  itemPath: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/pl7kjei7a626fehjgk37v6arz4"
