# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-secret
spec:
  itemPath: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/lb62qrobhdlz5nysvq6zcjl4vi"
