---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  namespace: mon
  labels:
    alertmanagerConfig: example
spec:
  receivers:
    - name: discord
      webhookConfigs:
      - url: http://alertmanager-discord:9094
        sendResolved: true
    - name: 'pushover'
      pushoverConfigs:
      - userKey: 
          name: pushover-config
          key: userKey
        token: 
          name: pushover-config
          key: token
        sendResolved: true
  route:
    groupBy: ['job']
    groupWait: 45s
    groupInterval: 10m
    repeatInterval: 30m
    receiver: discord
  
---
apiVersion: v1
data:
  token: YWl5ZGttc2kzbnQ3ZmIzM3R0enNpcmNvYmVveDJr
  userKey: dWpxaHZoNGg2YWd2MWR2ZWN2MThha2NlNmoxZnY4
kind: Secret
metadata:
  creationTimestamp: null
  name: pushover-config
---
apiVersion: v1
data:
  apiURL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvOTEyNDI5ODU0MTUzMTQyMjgyL1ZZSl8yZEt0YU9qT1FRTlhQaVBWbUJCeE80emdjd3AwSlAydER3aGN4SzYwaGVNMGxwdjhBVkhKSW9ObkNWN1pYR2w3L3NsYWNr
kind: Secret
metadata:
  creationTimestamp: null
  name: discord-config
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
  namespace: mon
spec:
  replicas: 2
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-example
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: example
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    role: alert-rules
    prometheus: hindsight
  name: prometheus-example-rules
  namespace: mon
spec:
  groups:
  - name: ./ffxiv.rules
    rules:
    - alert: Heartbeat
      expr: "(time() - max by (character) (ffxiv_heartbeat)) > 600"
      labels:
        namespace: mon
        severity: medium  
      annotations:
        summary: "No heartbeat"   
        description: "{{ $labels.character }} (pid {{ $labels.pid }}) hasn't shown signs of life for {{ humanize $value }} seconds"
    - alert: Leves
      expr: "ffxiv_leve_allowances > 100"
      labels:
        namespace: mon
        severity: medium  
      annotations:
        summary: "Too many leves" 
        description: "{{ $labels.character }} has {{ $value }} leve allowances"
    - alert: Inventory space
      expr: "ffxiv_inventory_free_slots < 5"
      labels:
        namespace: mon
        severity: medium  
      annotations:
        summary: "Low inventory space"
        description: "{{ $labels.character }} has {{ $value }} free inventory slots"
    # - alert: Missing FC XP buff
    #   expr: "ffxiv_heat_of_battle_ii != 0"
    #   labels:
    #     namespace: mon
    #     severity: medium  
    #   annotations:
    #     summary: "No Heat of Battle II buff found"
    #     description: "{{ $labels.character }} needs Heat of Battle II"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
  namespace: mon
spec:
  selector:
    matchLabels:
      name: alertmanager-discord
  replicas: 1
  template:
    metadata:
      labels:
        name: alertmanager-discord
    spec:
      containers:
      - image: benjojo/alertmanager-discord
        name: alertmanager-discord
        env:
          - name: DISCORD_WEBHOOK
            value: 'https://discord.com/api/webhooks/912458193509158932/m_-GpkWsDZd2XHHX2GJjPrShLtvKwi1T_HzRlgH4dnvToljxT9D1v7jaWlR6sEgl6ExO'
        ports:
        - containerPort: 9094
          name: http
        resources:
          limits:
            cpu: 500m
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
spec:
  ports:
  - name: http
    port: 9094
    protocol: TCP
    targetPort: http
  selector:
    name: alertmanager-discord