---
apiVersion: v1
kind: Service
metadata:
  name: knode1
  namespace: mon
  labels:
    app: netdata
spec:
  type: ExternalName
  externalName: knode1.lga1.radoncanyon.com
---
apiVersion: v1
kind: Endpoints
metadata:
  name: knode1
  namespace: mon
  labels:
    name: knode1
    app: netdata
subsets:
- addresses:
  - ip: 192.168.222.143
  ports:
  - name: netdata
    protocol: TCP
    port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: knode2
  namespace: mon
  labels:
    app: netdata
spec:
  type: ExternalName
  externalName: knode2.lga1.radoncanyon.com
---
apiVersion: v1
kind: Endpoints
metadata:
  name: knode2
  namespace: mon
  labels:
    app: netdata
subsets:
- addresses:
  - ip: 192.168.222.144
  ports:
  - name: netdata
    protocol: TCP
    port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: matisse
  namespace: mon
  labels:
    app: prometheus
spec:
  type: ExternalName
  externalName: 192.168.239.211
---
apiVersion: v1
kind: Endpoints
metadata:
  name: matisse
  namespace: mon
  labels:
    app: prometheus
subsets:
- addresses:
  - ip: 192.168.239.211
  ports:
  - name: prometheus
    protocol: TCP
    port: 9182
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: mon
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
  - port: prometheus
    path: /metrics
    params:
      format:
        - prometheus
    interval: 10s
    scheme: http
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netdata
  namespace: mon
  labels:
    app: netdata
spec:
  selector:
    matchLabels:
      app: netdata
  endpoints:
  - port: netdata
    path: /api/v1/allmetrics
    params:
      format:
        - prometheus
    interval: 10s
    scheme: http
    honorLabels: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mon-prometheus
  labels:
    name: mon-prometheus
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  iscsi:
    iqn: iqn.2014-09.com.radoncanyon:nas1:prometheus
    targetPortal: 192.168.222.149
    lun: 1
    fsType: ext4
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: hindsight
  namespace: mon
spec:
  storage:
    volumeClaimTemplate:
      spec:
        selector:
          matchLabels:
            name: mon-prometheus
        resources:
          requests:
            storage: 1Ti
  serviceAccountName: prometheus
  # monitor all namespaces
  # https://blog.coffeeapplied.com/prometheus-operator-service-monitor-auto-discovery-across-all-namespaces-4385b972b3e6
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  retention: 90d
  retentionSize: 800GB
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-hindsight
  namespace: mon
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.222.235
  externalTrafficPolicy: Local
  ports:
  - name: web
    port: 9090
    protocol: TCP
  selector:
    prometheus: hindsight
