---
apiVersion: v1
kind: Service
metadata:
  name: knode1
  namespace: mon
  labels:
    app: netdata
spec:
  type: ExternalName
  externalName: knode1.lga1.radoncanyon.com
---
apiVersion: v1
kind: Endpoints
metadata:
  name: knode1
  namespace: mon
  labels:
    name: knode1
    app: netdata
subsets:
- addresses:
  - ip: 192.168.222.143
  ports:
  - name: netdata
    protocol: TCP
    port: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: knode2
  namespace: mon
  labels:
    app: netdata
spec:
  type: ExternalName
  externalName: knode2.lga1.radoncanyon.com
---
apiVersion: v1
kind: Endpoints
metadata:
  name: knode2
  namespace: mon
  labels:
    app: netdata
subsets:
- addresses:
  - ip: 192.168.222.144
  ports:
  - name: netdata
    protocol: TCP
    port: 19999
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netdata
  namespace: mon
  labels:
    app: netdata
spec:
  selector:
    matchLabels:
      app: netdata
  endpoints:
  - port: netdata
    path: /api/v1/allmetrics
    params:
      format:
        - prometheus
    interval: 5s
    scheme: http
    honorLabels: true
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: hindsight
  namespace: mon
spec:
  serviceAccountName: prometheus
  # monitor all namespaces
  # https://blog.coffeeapplied.com/prometheus-operator-service-monitor-auto-discovery-across-all-namespaces-4385b972b3e6
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  remoteWrite:
    - url: 'http://influxdb:8086/api/v1/prom/write?db=prometheus'
  remoteRead:
    - url: 'http://influxdb:8086/api/v1/prom/read?db=prometheus'
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-hindsight
  namespace: mon
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.222.235
  externalTrafficPolicy: Local
  ports:
  - name: web
    port: 9090
    protocol: TCP
  selector:
    prometheus: hindsight
