---
# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml.tmpl
k8sServiceHost: "192.168.222.245"
k8sServicePort: "6443"
kubeProxyReplacement: true
installNoConntrackIptablesRules: true
bpfClockProbe: true
bgpControlPlane:
  enabled: true
ipam:
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: [ "10.43.16.0/20" ]
    clusterPoolIPv4MaskSize: 24
routingMode: "native"
autoDirectNodeRoutes: true
directRoutingSkipUnreachable: true
ipv4:
  enabled: true
enableIPv4BIGTCP: true
ipv6:
  enabled: false
ipv4NativeRoutingCIDR: "10.43.0.0/16"
bpf:
  dataPathMode: netkit
  masquerade: true
  lbExternalClusterIP: true
  hostLegacyRouting: false
  tproxy: true
  distributedLRU:
    enabled: true
  mapDynamicSizeRatio: 0.08
  events:
    monitorInterval: "10s"
    default:
      rateLimit: 10000
      burstLimit: 50000
  disableExternalIPMitigation: true
loadBalancer:
  mode: snat
socketLB:
  enabled: true
ipMasqAgent:
  enabled: true
  config:
    nonMasqueradeCIDRs:
    - 10.0.0.0/8
    masqLinkLocal: false
    masqLinkLocalIPv6: false
bandwidthManager:
  enabled: true
  bbr: true
vlanBypass: 0
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
  eventQueueSize: 32768
MTU: 1480
