apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-token
  namespace: media
spec:
  encryptedData:
    PLEX_TOKEN: AgB2UMh1CeSZ9WRjF5yPw3SynA23KPZEdwTdfQsqpAnlYWAw7SItZlZbNsvpIa+tgcgbJMyPHf/ERzKduxOWoxJxvm5NlT8YCrF4JA47uoJ1P3ow0OqbJX+vduZjj1pUZ6BEh1aqCGuwL/icCXLFsYJSeQiRxfiPGPlCzgnaPsYMutoktHvi72pUzbkM6l4WdLV4K1Z7MaCdQ2AebEicgQK4TAhl2R//BayvmHa2yCJgFdko7+wQ2XO/5zJbk/B6ITl1NoW4ZYwHm9fzI5Ov23gQMzHpuq29xf6ikzFavUPl5haJ+/myfAR/ogf4ReWkVovlBKmhk/JP3XWOULOiWqBN6lj2F6/FDJHelbjhdqa66N8E1dvYOR3F/vb9xB8re4GkUOiBEffSg2YywdNGcG/h5FNeeoYj2sIfLlOXmWtK4fR8W/QcKyJbNYZtTEg9rPl/MrVjq82W2vfHyuTHDPExERXHPo8mperwXhf1PWL4TaZwekPOF+GXJ+Gk5RS663FD9U+FQnT1SjhRrk6wjwsOg/AHoNcGq0g27jFb95fIp0oFoQPCuF/CnszD1QwHUX+nUs+Ru70JNE55fdVxwdATRahUUqG70O8xbcN5auKwsJeRHhT5Qi52ldkubaBnvqoTkX4bsOmJXRoWX5slB6AMPLjDoTuchzTkHqtieN1eJWnfHvtyPGgsr62GJ1f/qcKnQ6LN6a7dOoNbyS3u68kQNwlPjA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: plex-token
      namespace: media
