apiVersion: v1
kind: Service
metadata:
  name: pms
  namespace: media
spec:
  selector:
    app: pms
  type: LoadBalancer
  loadBalancerIP: 192.168.222.231
  externalTrafficPolicy: Local
  ports:
  - name: pms
    port: 32400
