apiVersion: v1
kind: Service
metadata:
  name: pms
  namespace: media
  labels:
    app: pms
    version: v1
  annotations:
     "lbipam.cilium.io/ips": "10.0.10.231"
spec:
  type: LoadBalancer
  selector:
    app: pms
    version: v1
  externalTrafficPolicy: Local
  ports:
    - name: https
      port: 32400
      targetPort: 32400
