---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pms
  namespace: media
  annotations:
    flux.weave.works/automated: "false"
spec:
  serviceName: pms
  replicas: 1
  selector:
    matchLabels:
      app: pms
  template:
    metadata:
      labels:
        app: pms
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: knode1
      volumes:
        - name: pms-iscsi
          iscsi:
            iqn: iqn.2014-09.com.radoncanyon:nas1:pms
            targetPortal: 192.168.220.149
            lun: 1
            fsType: ext4
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: transcode
          emptyDir:
            medium: Memory
      containers:
        - name: pms
          image: plexinc/pms-docker:1.25.5.5492-12f6b8c83
          # image: alpine
          # command: ["sleep"]
          # args: ["10000000"]
          resources:
            limits:
              gpu.intel.com/i915: 1
          volumeMounts:
            - name: pms-iscsi
              subPath: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: media
              mountPath: /media
              readOnly: true
          env:
            - name: CHANGE_CONFIG_DIR_OWNERSHIP
              value: "false"
            - name: PLEX_UID
              value: "1001"
            - name: PLEX_GID
              value: "1001"
            - name: TZ
              value: "America/New_York"
          ports:
            - name: pms
              containerPort: 32400
            - name: webtools
              containerPort: 33400
          readinessProbe:
            tcpSocket:
              port: pms
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: pms
            initialDelaySeconds: 15
            periodSeconds: 20
