---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pms
  namespace: media
  labels:
    app: pms
    version: v1
spec:
  serviceName: pms
  replicas: 1
  selector:
    matchLabels:
      app: pms
      version: v1
  template:
    metadata:
      labels:
        app: pms
        version: v1
        rclone-mounts: "true"
      annotations:
        ad.datadoghq.com/pms.logs: |
          [
            {
                "type": "file",
                "path": "/mnt/logs/pms/*.log",
                "source": "pms",
                "service": "pms"
            },
            {
                "type": "file",
                "path": "/mnt/logs/pms/*/*.log",
                "source": "pms",
                "service": "pms"
            }
          ]
    spec:
      nodeName: knode1
      serviceAccountName: pms

      # https://forums.plex.tv/t/request-for-participants-pms-1-23-x-dns-investigation/717155/57
      dnsConfig:
        options:
          - name: ndots
            value: "1"

      containers:
        - &pms
          name: pms
          image: lscr.io/linuxserver/plex:version-1.32.1.6999-91e1e2e2c

          # image: alpine
          # command: ["sleep"]
          # args: ["infinity"]
          resources:
            limits:
              gpu.intel.com/i915: "1"
          env:
            - name: CHANGE_CONFIG_DIR_OWNERSHIP
              value: "false"
            - name: PLEX_UID
              value: "1001"
            - name: PLEX_GID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"
            - name: VERSION
              value: "docker" # don't auto update
          ports:
            - name: http-pms
              containerPort: 32400
          volumeMounts:
            - name: pms-iscsi
              mountPath: /config
            - name: tmp
              mountPath: /tmp
            - name: media-rclone
              mountPath: /media
              readOnly: true
            - name: logs
              mountPath: /logs-pms
              subPath: pms
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - test -f /media/.anchors/dropbox
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: pms-iscsi
          persistentVolumeClaim:
            claimName: pms-iscsi-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
        - name: tmp
          emptyDir:
            medium: Memory
      initContainers:
        - <<: *pms
          name: plex-db-repair
          livenessProbe: null
          command:
            - sh
            - -c
            - curl https://raw.githubusercontent.com/ChuckPa/PlexDBRepair/a38da9e44eba13c5a8646d39050fb26ef1c94bca/DBRepair.sh | bash -x -s - 1 4 3 9
