---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pms
  namespace: media
spec:
  serviceName: pms
  replicas: 1
  selector:
    matchLabels:
      app: pms
  template:
    metadata:
      labels:
        app: pms
        rclone-mounts: "true"
    spec:
      nodeName: knode1

      # https://forums.plex.tv/t/request-for-participants-pms-1-23-x-dns-investigation/717155/57
      dnsConfig:
        options:
          - name: ndots
            value: "1"

      containers:
        - name: pms
          image: lscr.io/linuxserver/plex:version-1.28.2.6106-44a5bbd28
          # image: alpine
          # command: ["sleep"]
          # args: ["infinity"]
          resources:
            limits:
              gpu.intel.com/i915: "1"
          env:
            - name: CHANGE_CONFIG_DIR_OWNERSHIP
              value: "false"
            - name: PLEX_UID
              value: "1001"
            - name: PLEX_GID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"
          ports:
            - name: pms
              containerPort: 32400
          volumeMounts:
            - name: pms-iscsi
              mountPath: /config
            - name: tmp
              mountPath: /tmp
            - name: media-rclone
              mountPath: /media
              readOnly: true
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - test -f /media/.anchors/dropbox
            periodSeconds: 10
            failureThreshold: 1
      volumes:
        - name: pms-iscsi
          persistentVolumeClaim:
            claimName: pms-iscsi-pvc
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
        - name: tmp
          emptyDir:
            medium: Memory
