---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pms
  namespace: media
spec:
  serviceName: pms
  replicas: 1
  selector:
    matchLabels:
      app: pms
  template:
    metadata:
      labels:
        app: pms
        rclone-mounts: "true"
    spec:
      nodeName: knode1
      # https://forums.plex.tv/t/request-for-participants-pms-1-23-x-dns-investigation/717155/57
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:

        - name: pms
          image: lscr.io/linuxserver/plex:version-1.28.0.5999-97678ded3
          # image: alpine
          # command: ["sleep"]
          # args: ["infinity"]
          resources:
            limits:
              gpu.intel.com/i915: "1"
          env:
            - name: CHANGE_CONFIG_DIR_OWNERSHIP
              value: "false"
            - name: PLEX_UID
              value: "1001"
            - name: PLEX_GID
              value: "1001"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"
          ports:
            - name: pms
              containerPort: 32400
          volumeMounts:
            - name: pms-iscsi
              subPath: config
              mountPath: /config
            # - name: pms-host
            #   mountPath: /config-host
            - name: transcode
              mountPath: /transcode
            - name: media-rclone
              mountPath: /media
              readOnly: true
      volumes:
        - name: pms-iscsi
          iscsi:
            iqn: iqn.2014-09.com.radoncanyon:nas1:pms
            targetPortal: 192.168.222.149
            lun: 1
            fsType: ext4
        # - name: media
        #   persistentVolumeClaim:
        #     claimName: media
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
        - name: transcode
          emptyDir:
            medium: Memory
        # - name: pms-host
        #   hostPath:
        #     path: /mnt/BLOCK/pms
        #     type: Directory
