apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-smb-config
  namespace: palworld
data:
  smb.conf: |-
    [global]
        server string = samba
        idmap config * : range = 3000-7999
        security = user
        server min protocol = SMB2
        map to guest = never
        guest ok = no

        load printers = no
        printing = bsd
        printcap name = /dev/null
        disable spoolss = yes

        host msdfs = no
        wide links = yes
        follow symlinks = yes
        unix extensions = no
        acl allow execute always = yes

        ea support = yes

    [saves]
        path = /storage
        comment = Shared
        browseable = yes
        writable = no
        read only = yes
