# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: palworld-smb-credentials
spec:
  itemPath: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/4ivwyu4p5esgscrespx5sjbpsq"
