# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/ingress-networking-v1.json
# Palworld Save Games WebDAV Ingress
#
# Tailscale ingress with HTTPS for the rclone WebDAV server.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: palworld-webdav
  namespace: palworld
  annotations:
    tailscale.com/proxy-group: heimdall
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - brave-flamingo-saves
  defaultBackend:
    service:
      name: palworld-webdav
      port:
        name: http
