---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms
  labels:
    app: pms
    version: v1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pms
      version: v1
  template:
    metadata:
      labels:
        app: pms
        version: v1
    spec:
      serviceAccountName: pms
      containers:
      - &pms
        name: pms
        # IMAGE=ghcr.io/linuxserver/plex; skopeo --override-os linux list-tags "docker://${IMAGE}" | jq -r '.Tags[]' | sort -V | tail -n1
        image: ghcr.io/linuxserver/plex:version-1.41.9.9961-46083195d
        # image: alpine
        # command: [ "sleep" ]
        # args: [ "infinity" ]
        resources:
          limits:
            gpu.intel.com/i915: "1"
        env:
        - name: DO_DB_REPAIR
          value: "false"
        - name: DB_REPAIR_REV
          value: "e2a3d1d04b0b16e5e53931baa489fe76ac3b4129"
        - name: CHANGE_CONFIG_DIR_OWNERSHIP
          value: "false"
        - name: PLEX_UID
          value: "1001"
        - name: PLEX_GID
          value: "1001"
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/New_York"
        - name: VERSION
          value: "docker" # don't auto update
        ports:
        - name: https
          containerPort: 32400
        volumeMounts:
        - name: pms
          mountPath: /config
        # - name: pms-iscsi
        #   mountPath: /config-iscsi
        - name: tmp
          mountPath: /tmp
        - name: media
          mountPath: /media
          readOnly: false
      volumes:
      - name: pms
        persistentVolumeClaim:
          claimName: pms
      # - name: pms-iscsi
      #   persistentVolumeClaim:
      #     claimName: pms-iscsi-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: tmp
        emptyDir:
          medium: Memory
      initContainers:
      - !!merge <<: *pms
        name: plex-db-repair
        livenessProbe: null
        command:
        - sh
        - -c
        - '[ "${DO_DB_REPAIR:-false}" = "false" ] && exit 0 || (curl https://raw.githubusercontent.com/ChuckPa/PlexDBRepair/${DB_REPAIR_REV:-master}/DBRepair.sh | bash -s - auto prune exit)'
        ports: []
