---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms
  labels:
    app: pms
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
