# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/snapshot.storage.k8s.io/volumesnapshot_v1.json
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pms-config-restore
  namespace: pms
spec:
  volumeSnapshotClassName: nas1-mtank-iscsi
  source:
    volumeSnapshotContentName: pms-config-restore-content
