---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr4k
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
    nginx.ingress.kubernetes.io/auth-tls-secret: "ingress-nginx/auth-tls-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "required"
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - o.desertbluffs.com
  rules:
    - host: o.desertbluffs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr4k
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr4k-api
  namespace: media
  annotations:
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
    nginx.ingress.kubernetes.io/auth-tls-secret: "ingress-nginx/auth-tls-secret"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "required"
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - o.desertbluffs.com
  rules:
    - host: o.desertbluffs.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sonarr4k
                port:
                  name: http
