---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr4k
  namespace: media
spec:
  serviceName: sonarr4k
  replicas: 1
  selector:
    matchLabels:
      app: sonarr4k
  template:
    metadata:
      labels:
        app: sonarr4k
        rclone-mounts: "true"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"

      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pms
              topologyKey: "kubernetes.io/hostname"

      containers:
        - name: sonarr4k
          # crane ls lscr.io/linuxserver/sonarr | rg '^develop-4.*ls.*$' | sort -V | tail -n1 | pbcopy
          image: lscr.io/linuxserver/sonarr:develop-4.0.5.1719-ls64

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              memory: "1Gi"

          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"

          ports:
            - name: http
              containerPort: 8989

          volumeMounts:
            - name: sonarr4k
              subPath: config
              mountPath: /config
            - name: media-nfs
              mountPath: /media
            - name: scratch
              mountPath: /downloads
              subPath: downloads

          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - test -f /media/.anchors/dropbox
          #   periodSeconds: 10
          #   failureThreshold: 3

          startupProbe:
            httpGet:
              port: http
              path: /
            periodSeconds: 10
            failureThreshold: 30

      volumes:
        - name: sonarr4k
          persistentVolumeClaim:
            claimName: sonarr4k-iscsi-pvc
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
        - name: media-nfs
          persistentVolumeClaim:
            claimName: media
