---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr4k
  namespace: media
spec:
  serviceName: sonarr4k
  replicas: 1
  selector:
    matchLabels:
      app: sonarr4k
  template:
    metadata:
      labels:
        app: sonarr4k
    spec:
      nodeSelector:
        workload: download
      containers:
      - name: sonarr4k
        image: lscr.io/linuxserver/sonarr:version-3.0.7.1477
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/New_York'
        ports:
        - name: sonarr
          containerPort: 8989
        readinessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: sonarr
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: sonarr4k
          subPath: config
          mountPath: /config
        - name: media-rclone
          mountPath: /mnt/media-rclone
      volumes:
      - name: sonarr4k
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:sonarr4k
          targetPortal: 192.168.222.149
          lun: 1
          fsType: ext4
      - name: rclone
        hostPath:
          path: /mnt/media-rclone
          type: Directory
