---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-iscsi-pvc
  namespace: media
spec:
  volumeName: filebrowser-iscsi-pv
  resources:
    requests:
      storage: 1G
  accessModes:
    - ReadWriteOnce
