---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: media
spec:
  selector:
    app: filebrowser
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: http
