---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: filebrowser
  namespace: media
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.filebrowser: 'regex:^v2\.[0-9\.]+$'
spec:
  serviceName: filebrowser
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: scratch
        persistentVolumeClaim:
          claimName: scratch
      - name: filebrowser
        iscsi:
          iqn: iqn.2014-09.com.radoncanyon:nas1:filebrowser
          targetPortal: 192.168.220.149
          lun: 1
          fsType: ext4
      - name: config
        configMap:
          name: filebrowser
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v2.4.0
        command: ["/filebrowser"]
        args:
        - --config
        - /etc/filebrowser.json
        volumeMounts:
        - name: config
          mountPath: /etc/filebrowser.json
          subPath: filebrowser.json
          readOnly: true
        - name: filebrowser
          subPath: data
          mountPath: /data
        - name: media
          mountPath: /srv/media
        - name: scratch
          mountPath: /srv/scratch
        ports:
        - containerPort: 8080
          name: filebrowser
