---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jackett
  namespace: media
spec:
  serviceName: jackett
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"

      containers:
        - name: jackett
          # IMAGE=lscr.io/linuxserver/jackett; echo -en "$IMAGE:$(crane ls $IMAGE | sort -V | tail -n1)" | pbcopy
          image: lscr.io/linuxserver/jackett:version-v0.22.450
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              memory: "256Mi"
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"
          ports:
            - name: http
              containerPort: 9117
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: jackett
              subPath: config
              mountPath: /config
      volumes:
        - name: jackett
          persistentVolumeClaim:
            claimName: jackett-iscsi-pvc
