# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: atuin
spec:
  selector:
    app: atuin
  ports:
  - name: http
    port: 80
    targetPort: 8888
