apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-0b4fab02-96b4-4ee6-a26c-098c5a81a7a1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: org.democratic-csi.nas1-mtank-iscsi
    fsType: ext4
    volumeHandle: pvc-0b4fab02-96b4-4ee6-a26c-098c5a81a7a1
    volumeAttributes:
      iqn: iqn.2014-09.com.radoncanyon:nas1:csi-pvc-0b4fab02-96b4-4ee6-a26c-098c5a81a7a1-nas1-mtank
      lun: "0"
      node_attach_driver: iscsi
      portal: nas1.lga1.radoncanyon.com:3260
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas1-mtank-iscsi
  volumeMode: Filesystem
