apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-993e48c0-3bb0-4930-a15b-0f2c87108acd
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: org.democratic-csi.nas1-mtank-iscsi
    fsType: ext4
    volumeHandle: pvc-993e48c0-3bb0-4930-a15b-0f2c87108acd
    volumeAttributes:
      iqn: iqn.2014-09.com.radoncanyon:nas1:csi-pvc-993e48c0-3bb0-4930-a15b-0f2c87108acd-nas1-mtank
      lun: "0"
      node_attach_driver: iscsi
      portal: nas1.lga1.radoncanyon.com:3260
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas1-mtank-iscsi
  volumeMode: Filesystem
