apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-b64ee534-98c7-4633-b2f6-0cfe84f57654
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: org.democratic-csi.nas1-mtank-nfs
    fsType: nfs
    volumeHandle: pvc-b64ee534-98c7-4633-b2f6-0cfe84f57654
    volumeAttributes:
      node_attach_driver: nfs
      provisioner_driver: freenas-api-nfs
      server: nas1.lga1.radoncanyon.com
      share: /mnt/mtank/k8s/vols/pvc-b64ee534-98c7-4633-b2f6-0cfe84f57654
  mountOptions:
  - nfsvers=4.1
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - noresvport
  - nofail
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas1-mtank-nfs
  volumeMode: Filesystem
