apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-ec0fb702-dc8e-4844-8fc6-27306217ab12
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: org.democratic-csi.nas1-mtank-iscsi
    fsType: ext4
    volumeHandle: pvc-ec0fb702-dc8e-4844-8fc6-27306217ab12
    volumeAttributes:
      iqn: iqn.2014-09.com.radoncanyon:nas1:csi-pvc-ec0fb702-dc8e-4844-8fc6-27306217ab12-nas1-mtank
      lun: "0"
      node_attach_driver: iscsi
      portal: nas1.lga1.radoncanyon.com:3260
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas1-mtank-iscsi
  volumeMode: Filesystem
