apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-185a964f-5252-4b0c-9147-4d3e391d0f96
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: pvc-185a964f-5252-4b0c-9147-4d3e391d0f96
