apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-0b4fab02-96b4-4ee6-a26c-098c5a81a7a1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-0b4fab02-96b4-4ee6-a26c-098c5a81a7a1
