apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nas1-recovery
  name: pvc-4f855363-5bdb-4d75-bdd1-14cc5cedadbe
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nas1-mtank-iscsi
  volumeName: pvc-4f855363-5bdb-4d75-bdd1-14cc5cedadbe
