apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nas1-recovery
  name: pvc-b64ee534-98c7-4633-b2f6-0cfe84f57654
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nas1-mtank-nfs
  volumeName: pvc-b64ee534-98c7-4633-b2f6-0cfe84f57654
