apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-8c485ceb-2a93-4b1c-b985-33eab910e26c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-8c485ceb-2a93-4b1c-b985-33eab910e26c
