apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nas1-recovery
  name: pvc-dabd95ee-fb47-4274-8e0e-fae74d052f21
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nas1-mtank-iscsi
  volumeName: pvc-dabd95ee-fb47-4274-8e0e-fae74d052f21
