---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr4k
  namespace: media
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
spec:
  tls:
    - hosts:
        - j.desertbluffs.com
  rules:
    - host: j.desertbluffs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr4k
                port:
                  number: 7878
