---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr4k-iscsi-pv
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:radarr4k
    lun: 1
    fsType: ext4
  mountOptions:
    - noatime
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: radarr4k-iscsi-pvc
    namespace: media
