---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr4k
  namespace: media
spec:
  serviceName: radarr4k
  replicas: 1
  selector:
    matchLabels:
      app: radarr4k
  template:
    metadata:
      labels:
        app: radarr4k
        rclone-mounts: "true"
    spec:
      nodeSelector:
        workload: download
      containers:
        - name: radarr4k
          image: lscr.io/linuxserver/radarr:version-4.1.0.6175

          volumeMounts:
            - name: radarr4k
              subPath: config
              mountPath: /config
            - name: media-rclone
              mountPath: /media
            - name: scratch
              mountPath: /downloads
              subPath: downloads

          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"

          ports:
            - name: radarr
              containerPort: 7878

          livenessProbe:
            httpGet:
              port: radarr
              path: /
            periodSeconds: 10
            failureThreshold: 3

          startupProbe:
            httpGet:
              port: radarr
              path: /
            periodSeconds: 10
            failureThreshold: 30

      volumes:
        - name: radarr4k
          iscsi:
            iqn: iqn.2014-09.com.radoncanyon:nas1:radarr4k
            targetPortal: 192.168.222.149
            lun: 1
            fsType: ext4
        - name: media-rclone
          hostPath:
            path: /mnt/media-rclone
            type: Directory
        # - name: media
        #   persistentVolumeClaim:
        #     claimName: media
        - name: scratch
          persistentVolumeClaim:
            claimName: scratch
