clusterSize: 1

couchdbConfig:
  couchdb:
    uuid: f0a91555a3fc467e96110077c6dce1d1

persistentVolume:
  enabled: true
  existingClaims:
  - persistentVolumeName: database-storage
    volumeName: database-storage
    claimName: database-storage
    volumeSource:
      iscsi:
        targetPortal: 192.168.222.149
        iqn: iqn.2014-09.com.radoncanyon:nas1:couchdb
        lun: 1
        fsType: ext4
      mountOptions:
      - noatime
  storageClass: "-"
  accessModes:
  - ReadWriteOnce
  size: 10Gi

ingress:
  enabled: true
  ingressClassName: tailscale
  hosts:
  - eldest-microchip
  tls: []
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/experimental-forward-cluster-traffic-via-ingress: "true"
