---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
