---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials-secret
  namespace: kube-system
spec:
  encryptedData:
    secret-access-key: AgDEQuEvObn9ovWWA6xTpOIJjeD7XX4Osfdl+B1lDJtrR2IxMeOov5JyoO6S7Gcow0dGxa/KIJnLjk4ZP6IV/UqVkF1XuBI2L+Hz3alvHawU++CEiHfBeaR+57TDqFwhPQ/EfHnXpk1bgSK3maIWxoxvhw6zgzrjE+vQohSJ3nHmT1loOCgrTNoBDvIgjpMbGuhcFDhb7EmpLBw7O2dxdISdCpmzUz0Je8oqIQ8woZ+/uBU1l+DohI9mUJvNXsKNxsv1v3R0qIHkIeTgszVOVHRslfeC1sF9aznRQEdXPrg0qfvkISXxnOvDfsnjUcz1vq+iSVntOokvJWraNufCyQGq1pTSWQOcZF/0QJTV7OrTwiUEUnaACyEKiatgshbyMyFcEJUFuTtwv7pmPkxp/SyrSnLptEuDfsaWWbvR8eFrDwpHs8PLOKzazwsV3lS1E7oEr+8dHgTOwyAko9NaLUd0qR4AYEwR9MxPXFuo71sOaIg2LGngXTOSfBVEDK1JMotJDjuXlwpF4eNQHIXVbL0+RiLkRqxEcjC/1GWqUuTAJJXu70zZIbQrKjw7qMGgDe9TjgAWrPVTOxMwW6JByvymucEdb8mGGaFV+XkAa5CcxsDeh3GuQBPaZtxXKoXq/7SMxt8rjlN1rp3W1G8QiIImyKPvmGw5O/JQ56uzmAqIuHv8tVM8jzKdm8S/+cmMMiMO/c/PUCqHMFTDJiVoM2bA61KfZYXO0Ppa4yPprxQE8GfSluHd
  template:
    metadata:
      name: cloudflare-credentials-secret
      namespace: kube-system
