---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "nlopez@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@aethertrail.com
            secretAccessKeySecretRef:
              name: cloudflare-credentials-secret
              key: secret-access-key
        selector:
          matchLabels:
            use-cloudflare-solver: "true"
