apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials-secret
  namespace: kube-system
spec:
  encryptedData:
    secret-access-key: AgCYu/IWRuJHER8s+7J6Gj19QbPzMVXhZyBismU1UnZVxt0nEWe2YLPj4RTHZtvfGRi18oDuAl7R00KOG8Ci4XKI6WMhBjy7c3GSocC9CgvD+bIZSWgM/bkXjktd4eyVMWD5akYmv6199ySFOUHMvMKxZdtoP5CMqAU/sidi5IF/LTojrzI0Lfe4O/zmgf6Q7b9sor1pZqTaVoh8WemJ88ROp5QH8bfqaNtH4le4CKwuPbjQyiAtRN/TzzJdl1iKdqWqO/yEkbr9mBdzbwOhYnfm9vwl6emyQgvBM8BELOwh4G2pGyq87d4UB8L4yCsPS5aKrIgY34dSC6KEUHD02yEKSPjmic+lZ3V9+61cVEueXMtGvifidkyP3xPY5BoWcOwlqioJ+WMleXWWNbdQkNjf4LZg1Vhe7htr77wDmB1TKrAdIEFOgTPYi6PT9IQzGad2+MKmiaDXgRy5XMzaFmTPVnCo+CtdIe6DTwJM6akwJQJfeQyfMcUM/D6eqjz5tMgM7VaSRhEieQGIugUbWEYoA7pXITg3UEU5cCLSo/koOLf2epLc8PLdPJLCvsKGDTyH3UEKVEN7RRNGsie5/NEtQxyjSLM1Vp4OOQ3ADh0wPZVvG620measYBaIK2yUc+XIvFHOzVEHFKfhcBfcsp58ebKEfB0BZ3ub7tKdCkU4MWUyzMhoiyIIxolXzXHuXZG9zdBz5nGj5pO+mlV73Y4FQ0h7me+AELYFCJC7wCC1nQFcmyKbT/JQ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: route53-credentials-secret
      namespace: kube-system
