apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: netbox
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - q.desertbluffs.com
  rules:
  - host: q.desertbluffs.com
    http:
      paths:
      - backend:
          serviceName: netbox
          servicePort: netbox
