apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dui
  namespace: jobs
spec:
  schedule: '12 */1 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: dui
            iscsi:
              iqn: iqn.2014-09.com.radoncanyon:nas1:dui
              targetPortal: 192.168.220.149
              lun: 1
              fsType: ext4
          - name: dui-config
            secret:
              secretName: dui-config
          - name: dui-rclone-config
            secret:
              secretName: dui-rclone-config
          initContainers:
          - name: dui
            image: nlopez/dui:4
            env:
              - name: DUI_INI
                value: /dui/config/dui.ini
            volumeMounts:
            - name: dui
              mountPath: /dui
            - name: dui-config
              mountPath: /dui/config
              readOnly: true
          - name: rclone
            image: rclone/rclone:1.50.2
            args:
            - --config
            - /config/rclone.conf
            - copy
            - --progress
            - /dui/data
            - Nextcloud:/dui
            volumeMounts:
            - name: dui
              mountPath: /dui
              readOnly: true
            - name: dui-rclone-config
              mountPath: /config
              readOnly: true
          containers:
          - name: hc-ping
            image: buildpack-deps:bionic-curl
            command: ["/usr/bin/curl"]
            args:
            - --retry
            - '3'
            - https://hc-ping.com/4bb27667-5f75-46ed-ac59-a1a04dd54008
          restartPolicy: Never
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dui-config
  namespace: jobs
spec:
  encryptedData:
    dui.ini: AgBxdv6rDb73MPfrxJz49PmvTPt/Km7R6kKmvIdZb2F1Rlv3c5+kykBU23X38D9W9IvtY7Gjnk+aQAE9PQjSX+94jfER7bVtEJMG2RrWmc4VCyqZYS0xLAhTzyLC6lV/QBz6WlI1KmzbC6nahVvtqkaGuRWnkvAyVt47rbnChXtSm0vDGYz38sHplWxE/5+TiM/B531FjHw53/iG/l2jEV4xaFvvR1+M1SrhcdsMyRbip4R+k9jxxHDozaCfalRh+S0uXHmL6m+oZigfrA4vYTwe7phNTFYD4G4IFjJjNL2xFqC1rH93HotYNE2aFqqrEgdWbeEPuOBzTXbjI/l2inz4KenBZJpY5fdMSmm8oBFeschWt38ZUPlk6ZAxVYmpDWsiiZtx7C5jot4c/K+JdjSq2+zqM612wZWBx8JhMBlrt13rFqSaAHsJulmplogZ7w7+UPwmd9Z8s6T9B4fJP2Rg8amb1A1Wr/jyIOjyqOMExER3nezUiVKacTMdFX8FkFwbl5b4GuSIoIH2wJpLVN//w/7P6Z4puN8u6eDszWViRAG69h0ZQjWK8nL2v08kvNpRnph6rHw9ltRbPX25dNuzdJUC9f4auY2jkAnNgEmAI5+hQtfx6YD4EYo5AybyCLTiWAcw2d8b6BNJgL2Fwr09jEQZUDQDqGHKIU6XbLE+6hZKq9FPQJn2GoGGd5Zjjy6O4ZKcoEVc9w/V+htGYQvoVVGoJndAwOLO++rId4RxXtXa+drMGV7W+jxm80qn+27/jkmv7evRplS5qeuyJN2qqzHO+RWGR/cbv0/dHW8tOl5A2/foYCEqpBJqrXsMzwzbjLNIUsQ47GIa9qrJdOlzBZlpRPZekUTDnLAU3A7N9z0tH/TSyWW6lJJOy/RVs5BAmEm/BW/HjJ1gKxo3VQhiWwKiN6Z01N1k+n+nSZoqaXhs8n4qFa9dsWJUWw5mWi5FZ1/DHs7iGEPZ/7yLVw9WoLJV1vHrGo8QYUx1RYXDqOaVIrslkMYeYOLfF8mWe3shCS4jPr/T+PnyWFvVo2In9Z+nOJOFb7oBrDlCUgbiqMtIIbwlLzehYzuywrKXlxLsOoF4ASkyCuHC8thM0uRMeawUOoopqA44X96uQr/OflCRVF/Eep7CLTCWce0lWkTmT852zcegjKxrw5XVxCvY3cl2hWehi7AbYADT5+mHSPO5YXnVMg9bkjLIaXvGvDy3EP6LFzV2mttPwzHYFd4lah9b3W/GyLLPfEBNqPG+I81z2lWv7xU=
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dui-rclone-config
  namespace: jobs
spec:
  encryptedData:
    rclone.conf: AgBlXZBt4Ww25FkxHsROBKCZeSNHFuSXMYchcxc1GkaJIEM7UtZz2PCSZ/bs94Sr0aSEQy4bd/80S0kgzMRWNBsCGdOr2fC/vkx+0dlKRRzpJcMvdZ2j1tw9mFl7mwor4lUIHGjKibhvh3V3KqnL5KjThCHA/pDsFaib6on36MS2KQbNnWyHyqso790d7hK4ME9vD9sMF8+ChhEidmorJL6hbK+oVWthLi3vESaPsr86S3PDel8U0x+kyOipltouSdddzPkDRxeCN3IgPr8G4c3Jac/61GjU+cbWgQU1yB/0CcmWjTbtT+KaL966/wZ8RP4MEgKBuLnD/GZxJDZ+woQsoyfIKath6QlGR09Q7b2ie7TGQwpclphBDlJj+EEKMjqVkYRMk0cf2p9w8O0tDNj1NIUQVfeQvpzowJDbVtgRvW5ViRStKAJqe3lp5yORxhXILq5kmLt3D79mnWeb307HVRetXyyAKtT/DJ6s4XhqSXyI8KnUREJhI5fs0wQE75T6NP9YZePwtgwvCJTDZfGCilLOOh4k2E4Ti4o71+i1ErRBYM7K23XVjPqGWQox8wFKipntStQq43nHWZIajufPYxZWFcCxaAi8nl5zImCUc5aRrknpfPEBAa5L528tSnop49cdL/Mn3bJ+ZKiCh9ZUQiOduGOvrFjKARMKW4/Wxy4Lnq3BWbhBcLVFXxs15AMxhoweYcyUksDOHSNHCKwqsaSCxkVJc2AriRXeOg0btKwuy4KTVp1pJju5YaF1Irc+piwjK+Xj8DEf3E1GtnE/9aRuKy9dxrchsbZ9v2F+01z6QRvmjh9cOBaOryPCJFB0FGBoy1Ni9hDLaKv8wLb7bAhE7WUz/8yIlTdTcqHGVu4oRbb64CUzlFPsa1q1IWSfrIoiETQH+oFuTG/dGWFEqgslxGRjvM1KGCRGr/CfVMT2
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dui-cache-clear
  namespace: jobs
spec:
  schedule: '0 0 * * 0'  # at 00:00 on Sunday
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: dui
            iscsi:
              iqn: iqn.2014-09.com.radoncanyon:nas1:dui
              targetPortal: 192.168.220.149
              lun: 1
              fsType: ext4
          containers:
          - name: dui
            image: nlopez/dui:4
            command: ["sh"]
            args: ["-c" , "rm -rfv /dui/*"]
            volumeMounts:
            - name: dui
              mountPath: /dui
          restartPolicy: Never
