---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscan
  namespace: media
data:
  config.yaml: |
    authentication:
      username: dark-opinion
      password: dYVgGujTZtGVHnxz2j3R

    # <- processor ->

    # default: 10m
    minimum-age: 2m

    # delay between processed scans
    # default: 5s
    scan-delay: 15s

    # override the interval scan stats are displayed:
    # defaults to 1 hour / 0s to disable
    scan-stats: 1h

    # set multiple anchor files
    anchors:
      # - /media/.anchors/nas2
      - /media/.anchors/dropbox

    # <- triggers ->

    # port for Autoscan webhooks to listen on
    port: 3030

    triggers:
      # inotify:
      #   - priority: 0
      #     include:
      #       - ^/media/
      #     exclude:
      #       - \.(srt|ass|nfo|txt)$
      radarr:
        - name: radarr   # /triggers/radarr
          priority: 2
        - name: radarr4k # /triggers/radarr4k
          priority: 5
      sonarr:
        - name: sonarr # /triggers/sonarr-docker
          priority: 2
        - name: sonarr4k
          priority: 5

    # <- targets ->

    targets:
      plex:
        - url: http://pms:32400 # URL of your Plex server
          token: v1JHkzy2eHR-Uyhg7wTP # Plex API Token
