---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: satisfactory-server-iscsi-pv
spec:
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:satisfactory-server
    lun: 1
    fsType: ext4
  mountOptions:
    - noatime
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: satisfactory-server-iscsi-pvc
    namespace: games
