---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-server-iscsi-pvc
  namespace: games
spec:
  volumeName: satisfactory-server-iscsi-pv
  resources:
    requests:
      storage: 100G
  accessModes:
    - ReadWriteOnce
