apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: palworld-game
  namespace: palworld
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: internet
    namespace: envoy-gateway-system
  rules:
  - backendRefs:
    - name: palworld
      port: 8211
