---
apiVersion: v1
kind: Namespace
metadata:
  name: dui
  labels:
    name: dui
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dui
  namespace: dui
spec:
  schedule: '12 */1 * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: dui
            iscsi:
              iqn: iqn.2014-09.com.radoncanyon:nas1:dui
              targetPortal: 192.168.222.149
              lun: 1
              fsType: ext4
          - name: dui-config
            secret:
              secretName: dui-config
          - name: dui-rclone-config
            secret:
              secretName: dui-rclone-config
          initContainers:
          - name: dui
            image: docker.io/nlopez/dui:4
            env:
              - name: DUI_INI
                value: /dui/config/dui.ini
            volumeMounts:
            - name: dui
              mountPath: /dui
            - name: dui-config
              mountPath: /dui/config
              readOnly: true
          - name: rclone
            image: docker.io/rclone/rclone:1.53.3
            args:
            - --config
            - /config/rclone.conf
            - copy
            - --progress
            - /dui/data
            - Nextcloud:/dui
            volumeMounts:
            - name: dui
              mountPath: /dui
              readOnly: true
            - name: dui-rclone-config
              mountPath: /config
              readOnly: true
          containers:
          - name: hc-ping
            image: buildpack-deps:bionic-curl
            command: ["/usr/bin/curl"]
            args:
            - --retry
            - '3'
            - https://hc-ping.com/4bb27667-5f75-46ed-ac59-a1a04dd54008
          restartPolicy: Never
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dui-config
  namespace: dui
spec:
  encryptedData:
    dui.ini: AgBnd8TRQMEFbSWcbM5xtW5+8KIamGhf38gE/CR9BTB/6n5G9RJhfMdsWMiLPWj7YF2DwftxCXhHrmP3+8/DXDqs2BMOOoRlVWnsA5l9/rHhAiHwoYtRLNxa3hAF4iX/r9zBIkb4IyeZiOoHdyUvs5QoI9R9p3QJnHF0lT+9KHbKEsQs1vhlwJWtPonoWQo10YoKc7h++vuqwHXv1+6Jokbw/n41ubdBxCqDfcYv8kbHyDGMtVEoYNaugVEucI2Vdzb+SzZsEDR29M9lFQVCe/+yKqYLGqT/uVAMRKP3F/XzeD/rVplyAOclnCb8F68JHSl7vfMQPHNT1uF3pD8TQmQyil8Lpiw8lXL5KPNT0pnhzwUbLi43zYQmSl3GgP7HtlrVyuq3sCzU/XhGQxDTwKc4GpiVY8L0KEGf4dTtNvv64RxX+/yVuWf6tOYH0JMftsjDvP34ExTAUj3GZ8P/2RshUu0GLcCXNNKECyEKI3BbNE0FOCjlQp5PWe5//AMq5gOn3o6RDdRPh2cLiRWbRfqCsYSAEydJnobnKNl1XTwuArrwooSSCS4VXWPy8UH0neAcAGJZSpuyeW5ZeVXcHmMgNYYuUpGjRCskqfddYzLbCpgxN2NnAfbbq+NHCQfKgs5f5TJTgG1So1I4cqt81jhQO5FRscPQrZhverFX3qelej5C+1+Q6iGXG4haD18GfpAz41LIxRkjlYneV/x/aKGoqftZKa1HAFDjf/8dGr6fq2aJv/3ul4gHV4F0Mugyk8We4P/oWiKIiSGOoJcjW2w75o5jrPcZo7yjJ0FwHiTlMyorWjBf9QOMmxL3+2wYV8T17fXy0o2dsH1z6mOo3PXczHxKmhrohRVdbIhIYHvxvvUPxOolkicfTjV4QCuZwSCqxlSo/m63ZCbaLBfn2+H+VtWcYno/BfM7z3A+ozKwbb4E9kaSb2GXrcLNYSb3Hvj/7zJko1haA7kRQMSHTK5tI75vMpZkT/6F8NvDRMPf2cuu3e6379sne1CU8CjbQwjVh+ndnl6T1sQMcQ1EbiOlpDd4hN94qT5DW5ybW74fkaDkbbo3WNHhamJNpOy5Iwp6H+2f5g8Vgfs7NZ1FljxiTIrhIe63D+P+15kvWBRLgFElP9a1omEny8NtG3SNzYq3BixSRiGrnpGOp649U7ZX5mFVFhoYZ39oOIJukGu5tYVvQJV6atFXmBQxIhbq08eDYyV+3r5RPHNgsKDVYxVyttfY/byUYSuVK+Vh7HIDQ0Yfo0Rcer4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dui-config
      namespace: dui
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dui-rclone-config
  namespace: dui
spec:
  encryptedData:
    rclone.conf: AgBFm4bx54IN1ljVNYZIo7WOkk5gFdqVF4qYTz5Zmqa2jPYLywLVwBpzoaiWveUoReMKsfU3kE+yga2KkYVIe7W8f46nELNKA6LPCWucnz/XUIREUIJ6E9FvrgxCfjzNxDnjOeA2FK5ZdXRng0GGTk9ifIrVGbEXMSKM2xHUjnaQPgvVhlNrpPLWdaoPnRMF9SnjxY6OdRrr3GsM991Jx/khXujj5r0ManbTYOR8wQeQ6IK9DrKH6S6r1DXwjf4quNclIoWiXX58A1oRth7zfVzkE3P4sKHxbvlHMmOCawf0gsXMSoplERMHaHv0cVmUV0m8mwJydOAWI/5JUXyWj55xkgM4U8qeS0ey0DqatTjlE8OzZglXSwgJw6q5LN9GymX980AT49CIMt7nzHJH2z0Ygtwr3LL8XUn1xGpj6zSaomTpbGrXprPC1xU9kJ+25ziPL2o4+vmOmCrdpsvEx7NDHfiJiI45hCDd3RLqUx4Sq9IQQBCAIdsw/AjJmqaIW1J7xC2sEHb9F6r1JoQNZ/rAonj17u0vsYs90S9sgRg9HA7ZRizaRoxDOiCIRZMe2XCJuvn5qhQ+QK2VtunJOlnLXyEkBd3IzTlooL/uncOVwz+Wp/AI0BGGNhgU7DmURURwbtoAnQ5TcthxVUw8DjcQiHRA9y4IZeqt+WCAXrQ8bQl7vjVCxbNIMIMrgN5jnThXaELiEKtTTsvbxGj7dVOOYoBYBEIhIG4j2UcfmkP6I51yJkTznv70iJbiBdTkDTp6a4wRPcxLY5JWEeLF1DbhYrUePKsS8dQQicLJL1jNu9+6FcORYG+8URt7HxzpohfbCoGorpv699tM0UJVtghVHbu+CB7CwT/DU/JykjSywPWkLjBLKjIal0D7S7s4pj3COb3+3MDce4MbYa5Kd8JpyMz2gDs2zbX/mZ9aT+xmOmM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dui-rclone-config
      namespace: dui
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dui-cache-clear
  namespace: dui
spec:
  schedule: '0 0 * * 0'  # at 00:00 on Sunday
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: dui
            iscsi:
              iqn: iqn.2014-09.com.radoncanyon:nas1:dui
              targetPortal: 192.168.222.149
              lun: 1
              fsType: ext4
          containers:
          - name: dui
            image: nlopez/dui:4
            command: ["sh"]
            args: ["-c" , "rm -rfv /dui/*"]
            volumeMounts:
            - name: dui
              mountPath: /dui
          restartPolicy: Never
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: dui
spec:
  podSelector: {}
  policyTypes:
  - Ingress
