operatorConfig:
  podAnnotations:
    operator.1password.io/item-path: "vaults/evjh25ux2mnoufaut6qhvm2pdi/items/2gsoxeyko7xgyz7ar6yqasjo54"
    operator.1password.io/item-name: "operator-oauth"
  logging: info
  image:
    repository: ghcr.io/tailscale/k8s-operator
    pullPolicy: IfNotPresent
proxyConfig:
  defaultTags: "tag:k8s,tag:home,tag:lga1"
  image:
    repository: ghcr.io/tailscale/tailscale
    pullPolicy: IfNotPresent
apiServerProxyConfig:
  mode: "true"
  allowImpersonation: "true"
