csiDriver:
  name: "org.democratic-csi.nas1-mtank-iscsi"
driver:
  existingConfigSecret: democratic-csi-nas1-mtank-driver-config
  config:
    driver: freenas-api-iscsi
controller:
  externalSnapshotter:
    enabled: true
storageClasses:
- name: nas1-mtank-iscsi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
  mountOptions:
  - noatime
volumeSnapshotClasses:
- name: nas1-mtank-iscsi
  deletionPolicy: Delete
  parameters: {}
