apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  labels:
    app: httpbin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
      - name: httpbin
        image: ghcr.io/mccutchen/go-httpbin:2.21
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status/200
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/200
            port: http
          initialDelaySeconds: 2
          periodSeconds: 5
