# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-nas1-mtank
spec:
  storageClassName: nas1-mtank-iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  dataSource:
    name: jellyfin-config-restore
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
