---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-iscsi-pvc
spec:
  volumeName: jellyfin-iscsi-pv
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-iscsi-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:jellyfin
    lun: 1
    fsType: ext4
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
