---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-jellyfin
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:jellyfin
    lun: 0
    fsType: ext4
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  volumeName: config-jellyfin
  resources:
    requests:
      storage: 100Gi
  accessModes:
  - ReadWriteOnce
