---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: warp-heartbeat
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: quay.io/curl/curl:8.13.0
            args:
            - --max-time
            - "5"
            - -verbose
            - --silent
            - --show-error
            - --socks5
            - warp.warp.svc.cluster.local:1080
            - https://cloudflare.com/cdn-cgi/trace
            - https://icanhazip.com
          restartPolicy: Never
