apiVersion: apps/v1
kind: Deployment
metadata:
  name: warp
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: warp
      version: v1
  template:
    metadata:
      labels:
        app: warp
        version: v1
    spec:
      restartPolicy: Always
      containers:
      - name: warp
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests: {}
          limits: {}
        command: ["sleep"]
        args: ["infinity"]
        volumeMounts:
        - name: warp
          mountPath: /var/lib/warp
        - name: warp-nas1-mtank
          mountPath: /var/lib/warp-new
      volumes:
      - name: warp
        persistentVolumeClaim:
          claimName: warp
      - name: warp-nas1-mtank
        persistentVolumeClaim:
          claimName: warp-nas1-mtank
