---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: warp
spec:
  capacity:
    storage: 10G
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.222.149
    iqn: iqn.2014-09.com.radoncanyon:nas1:warp
    lun: 1
    fsType: ext4
  mountOptions:
  - noatime
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warp
spec:
  volumeName: warp
  resources:
    requests:
      storage: 10G
  accessModes:
  - ReadWriteOnce
