---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warp
  labels:
    app: warp
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
