---
apiVersion: v1
kind: Service
metadata:
  name: warp
  annotations:
    tailscale.com/hostname: warp
spec:
  type: LoadBalancer
  ingressClass: tailscale
  selector:
    app: warp
  ports:
  - name: warp
    port: 1080
    targetPort: 1080
