---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: toolbox-cron
  namespace: media
spec:
  suspend: false
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          volumes:
            - name: media
              persistentVolumeClaim:
                claimName: media
            - name: scratch
              persistentVolumeClaim:
                claimName: scratch
            - name: yt-dlp-config
              configMap:
                name: toolbox-cron
                items:
                  - key: yt-dlp.conf
                    path: config
            - name: temp
              emptyDir: {}
          containers:
            - name: toolbox
              image: docker.io/nlopez/media-toolbox:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests: {}
                limits: {}
              command: ["yt-dlp"]
              args:
                - "--version"
              volumeMounts:
                - name: media
                  mountPath: /media
                - name: scratch
                  mountPath: /scratch
                - name: yt-dlp-config
                  mountPath: /home/user/.config/yt-dlp/config
                - name: temp
                  mountPath: /yt-dlp-temp
              securityContext:
                allowPrivilegeEscalation: false
              env: []
