# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-desertbluffs-com-cert-rsa
spec:
  secretName: wildcard-desertbluffs-com-cert-rsa
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
  - '*.desertbluffs.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-desertbluffs-com-cert-ecdsa
spec:
  secretName: wildcard-desertbluffs-com-cert-ecdsa
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - '*.desertbluffs.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
