---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/gateway.envoyproxy.io/envoyproxy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internet
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        allocateLoadBalancerNodePorts: false
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-admin-internet
  namespace: envoy-gateway-system
spec:
  type: ClusterIP
  selector:
    gateway.envoyproxy.io/owning-gateway-name: internet
    gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
  ports:
  - name: admin
    port: 15000
    targetPort: 15000
    protocol: TCP
