# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.envoyproxy.io/envoypatchpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: h2-websockets-internet
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: internet
  type: JSONPatch
  jsonPatches:
  - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
    name: "envoy-gateway-system/internet/wildcard-desertbluffs-com-https"
    operation:
      op: add
      path: "/filter_chains/0/filters/0/typed_config/http2_protocol_options"
      value:
        allow_connect: true
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: h2-websockets-private
  namespace: envoy-gateway-system
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: private
  type: JSONPatch
  jsonPatches:
  - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
    name: "envoy-gateway-system/private/wildcard-radoncanyon-com-https"
    operation:
      op: add
      path: "/filter_chains/0/filters/0/typed_config/http2_protocol_options"
      value:
        allow_connect: true
  - type: "type.googleapis.com/envoy.config.listener.v3.Listener"
    name: "envoy-gateway-system/private/wildcard-desertbluffs-com-https"
    operation:
      op: add
      path: "/filter_chains/0/filters/0/typed_config/http2_protocol_options"
      value:
        allow_connect: true
