apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: tls-session-resumption
spec:
  tls:
    session:
      resumption:
        stateless: {}
  targetSelectors:
  - group: gateway.networking.k8s.io
    kind: Gateway
