# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-config
  namespace: palworld
data:
  TZ: "UTC"
  PLAYERS: "16"
  PORT: "8211"
  QUERY_PORT: "27015"
  REST_API_PORT: "8212"
  PUID: "1000"
  PGID: "1000"
  MULTITHREADING: "false"
  COMMUNITY: "true"
  SERVER_NAME: "Brave Flamingo"
  SERVER_DESCRIPTION: "🦩"
  UPDATE_ON_BOOT: "true"
  RCON_ENABLED: "false"
  RCON_PORT: "25575"
  USE_BACKUP_SAVE_DATA: "true"
  BACKUP_ENABLED: "false"
  DELETE_OLD_BACKUPS: "false"
  OLD_BACKUP_DAYS: "30"
  BACKUP_CRON_EXPRESSION: "0 0 * * *"
  AUTO_UPDATE_ENABLED: "false"
  AUTO_REBOOT_ENABLED: "false"
  AUTO_PAUSE_ENABLED: "false"
  ENABLE_PLAYER_LOGGING: "true"
  DIFFICULTY: "None"
  DAYTIME_SPEEDRATE: "2.0"
  NIGHTTIME_SPEEDRATE: "1.0"
  EXP_RATE: "2.0"
  PAL_CAPTURE_RATE: "1.2"
  PAL_SPAWN_NUM_RATE: "2.9"
  PAL_DAMAGE_RATE_ATTACK: "1.0"
  PAL_DAMAGE_RATE_DEFENSE: "1.0"
  PLAYER_DAMAGE_RATE_ATTACK: "1.0"
  PLAYER_DAMAGE_RATE_DEFENSE: "1.0"
  DEATHPENALTY: "Item"
  ENABLE_PLAYER_TO_PLAYER_DAMAGE: "False"
  ENABLE_FRIENDLY_FIRE: "False"
  ENABLE_INVADER_ENEMY: "False"
  ENABLE_AIM_ASSIST_PAD: "True"
  ENABLE_AIM_ASSIST_KEYBOARD: "False"
  DROP_ITEM_MAX_NUM: "5000" # default: 3000
  BASE_CAMP_MAX_NUM: "128"
  BASE_CAMP_WORKER_MAX_NUM: "50" # default: 15
  BASE_CAMP_MAX_NUM_IN_GUILD: "10" # default: 4
  AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: "False"
  GUILD_PLAYER_MAX_NUM: "20"
  IS_MULTIPLAY: "False"
  IS_PVP: "False"
  HARDCORE: "False"
  ENABLE_NON_LOGIN_PENALTY: "False"
  ENABLE_FAST_TRAVEL: "True"
  IS_START_LOCATION_SELECT_BY_MAP: "True"
  EXIST_PLAYER_AFTER_LOGOUT: "False"
  REST_API_ENABLED: "True"
  SHOW_PLAYER_LIST: "True"
  BAN_LIST_URL: "https://api.palworldgame.com/api/banlist.txt"
  USEAUTH: "True"
  CROSSPLAY_PLATFORMS: "(Steam,Xbox,PS5,Mac)"
  ENABLE_PREDATOR_BOSS_PAL: "true"
  ALLOW_GLOBAL_PALBOX_EXPORT: "True"
  ALLOW_GLOBAL_PALBOX_IMPORT: "False"
  EQUIPMENT_DURABILITY_DAMAGE_RATE: "0"
  ITEM_CORRUPTION_MULTIPLIER: "0"
  DISABLE_GENERATE_ENGINE: "false"
  DISABLE_GENERATE_SETTINGS: "false"
  PLAYER_STAMINA_DECREASE_RATE: "0.8"
  PAL_AUTO_HP_REGEN_RATE: "3.0"
  PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: "5.0"
  PLAYER_AUTO_HP_REGEN_RATE: "3.0"
  PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP: "5.0"
  BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: "0" # default: 1
  COLLECTION_DROP_RATE: "3.0"
  COLLECTION_OBJECT_HP_RATE: "1.0"
  ENEMY_DROP_ITEM_RATE: "3.0"
  COLLECTION_OBJECT_RESPAWN_SPEED_RATE: "0.5" # lower is faster
  ITEM_WEIGHT_RATE: "0" # default: 1
  PAL_STAMINA_DECREASE_RATE: "0.1" # default: 1.0
  SUPPLY_DROP_SPAN: "30" # minutes (default: 180)
  PLAYER_STOMACH_DECREASE_RATE: "1.0"
  PAL_STOMACH_DECREASE_RATE: "1.0"
  WORK_SPEED_RATE: "2.0"
  PAL_EGG_DEFAULT_HATCHING_TIME: "0" # hours (default: 1)
  BLOCK_RESPAWN_TIME: "1" # seconds (default: 5, DO NOT SET TO 0 -- infinite?)
  ENABLE_GAMEDATA_API: "true"
