# Dynamically provisioned via democratic-csi (freenas-api-nfs)
# Dataset created on TrueNAS under mtank/k8s/vols/<pvc-uuid> (UUID assigned at provision time)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: savegames
  namespace: palworld
spec:
  storageClassName: nas1-mtank-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
