# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolumeclaim-v1.json
# Dynamically provisioned via democratic-csi (freenas-api-iscsi)
# Volume created on TrueNAS at mtank/k8s/vols/palworld-config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: palworld
spec:
  storageClassName: nas1-mtank-iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
