# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: palworld
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  storageClassName: nas1-mtank-iscsi
  resources:
    requests:
      storage: 20Gi
  accessModes:
  - ReadWriteOnce
