---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
spec:
  tls:
    - hosts:
        - login2.desertbluffs.com
  rules:
    - host: login2.desertbluffs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia
                port:
                  number: 9091
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: authelia
  namespace: ingress-nginx
spec:
  podSelector:
    matchLabels:
      app: authelia
  ingress:
  - ports:
    - port: 9091
    from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: ingress-nginx
spec:
  selector:
    app: authelia
  ports:
  - name: authelia
    port: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      volumes:
        - name: authelia-config
          projected:
            sources:
              - secret:
                  name: authelia-users
                  items:
                    - key: users.yaml
                      path: users.yaml
              - configMap:
                  name: authelia-custom
                  items:
                    - key: custom.yaml
                      path: custom.yaml
        - name: authelia-secrets
          secret:
            secretName: authelia-secrets
      containers:
        - name: authelia
          image: ghcr.io/authelia/authelia:4
          # image: alpine
          env:
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /secrets/jwt
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /secrets/session
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: storage_encryption_key
          ports:
            - name: authelia
              containerPort: 9091
          volumeMounts:
            - name: authelia-config
              mountPath: /config
              readOnly: true
            - name: authelia-secrets
              mountPath: /secrets
              readOnly: true
          # command: ["sleep"]
          # args: ["10000000"]
          command: ["authelia"]
          args: ["--config", "/config/custom.yaml"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-custom
  namespace: ingress-nginx
data:
  custom.yaml: |
    ---
    server:
      host: 0.0.0.0
      port: 9091
    access_control:
      default_policy: deny
      rules:
        - domain:
            - "*.desertbluffs.com"
          policy: one_factor
    authentication_backend:
      disable_reset_password: true
      file:
        path: /config/users.yaml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 1024
    storage:
      local:
        path: /tmp/db.sqlite3
    session:
      name: authelia_session
      expiration: 1h
      inactivity: 5m
      remember_me_duration:  1M  # 1 month
      domain: desertbluffs.com
    notifier:
      disable_startup_check: true
      filesystem:
        filename: /dev/null
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-users
  namespace: ingress-nginx
spec:
  encryptedData:
    users.yaml: AgCxd5fs1KGFFz8zt/AbA3Rp6TMrPkPyveJeNXeVO+CUMEXCtKziNLL1oSpCwI3uoTRW4oRN91YyOFV3QKFuTmDuAXp/acqvi9S1GwtLwpmic0PTbKb4DxxaJPUmVT4qhXoiBjT+N6UyVZDIpRimlcNxuQS9ha4Sl6vzyKh/6NC6AEZtJEzCX+Ft2sxH2SVkQ3/IQkDooBvL7KOBCteMH1VrHYohA3s/76a2lce3DJfMqUGet3fyCA9ElGXlMfHY9dQGhA85F97pL1O+XNvt7zlvo/e+oCdhmdQZtAxlVdIg+rt+40WUTVkYjylBvLNbV1y7q9GXQB1bImYQ8OAX/m4CBdiSLsNudV4UWxSqAzugIgkBiN9qG58ouCwsuUph4uAhEmg9p8KwmTT63U+YP97Zg+VOw39l9Drhq9s1lUORiKfravz41z1vMKNOqdhpT84XRqZF06Epxzltwq22+hgD9Cnemuk+ZOcsrFh/EbY9saHEoLznwppkamIlwQ0i0+GVyCzg8ISDpVfK6Nxb6naqW96fgAi9eU1U1SlrxffS33jIpBDZHlno9DeBH19ZNa8yQB7QXzn6Q9YmMgiUPuD7u/EwZjT8SYgpUjxyDJNXijL/7erZMJkrlYbhroJFrfMsKmxeAoKfm3eg2Y9Rgg/kCQ83RCQVrJzxFJANSQlodvn0B1JcGZG7+/5WgaCFBEYhChhrmG/qccdNMnX5EBgGWQgiSuHW5sY3schKL1kx0IexxxmTKxoF23MukNjp2vJFJleoJGAoOtLlrNfCXHuo91zfEUgkYHsjhe0D6MJYZ+xXk8lAxcH+h40IYiY+HGIC2HGy59owRGzUV7voB3zhlIV7DKoSFr55Vu9i22p8jjw89XVK/cbfejqXPX0MNXfS6HIoTBzsC3G/AEFix4EalAH9eBYZJCZ2qGS93hk1ZMHwE7ATZ7VWG6adfEpwm1T5/uZihegDDSj/590/1jAyYe3b6g==
  template:
    metadata:
      creationTimestamp: null
      name: authelia-users
      namespace: ingress-nginx
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-secrets
  namespace: ingress-nginx
spec:
  encryptedData:
    jwt: AgAAJBAwEEpq3p9ZBDTeHhdKIMOfISbA9vmxPa11hEzks3BbsJC+sRSK1uqwrO5Q8fcL4onXBQz6k3K+at6J4VKZN8JuKDTpjqx0bIo2XWgs/blM5UDzhWW6wQaXa+VTWADu5lSsLkqGOIkyME5RYj6jQZ9V7ac9fX9DmujkXY/tg6T22VOiI8NR0c1B73m6U9c49kYt3ShA0QNYgJSXaFV3OcWkfOde51MhBAZSzyMWOn8WHr8Ct06JfaGfjfOFW5uGRRmSPLFPuokFql5HK8JTqOwsDVjEsIaCOiYjuaAIcoybcaVshCapq6v9PsIf6GjywSDVJWjPqE4keBh7xvztYyRMXrdRsbShLSR9llG0z1yb2oJmmYw4pjx2wjHT4d7u0rjuLb3SOsFpNCyqJUSNeKFr5eyneKLBzGOHZLlUjL7zPgpTJvURehBDiGXN82zUj06vg2SETrvmD5vOFtaMwqPvsjS41roorMSkago7heL1EKrSBvzwUJHP5pSvhyItTtv9IT/QWlHWLkpBNxk9jQ/KjEDnONSUEnr20upSSwYh2YepeLC6YDrC9OKwQtAmu4jity9s5fQuiGDIzep5PuwdXdgKilaD+RwvEyAOPhEHR0NBsL2Li4m80Ts4BKtLmmf+oGdF1TwA+yB8actHcgtV7Umi7Sq5D3yfVBQEQHTDOw+7vsgIZiUb19NPNsIaK8n9LyRM1r1EYI2jM4GnFBjB4cKth8xs0cODSlLA4RR/VKVTLhJS4gUE6LNOG89SlGfYWZ6pRGLD2og5+wX8tKqNtWKsKK1jUePeqIN20eQ79n40x43SH+GqiHp4ee2giGsJ1kgQWfe7maTWfcgwmKSa58xTRp2OqJS71WccFg==
    session: AgBgV2nll4rCI/0TmNH20gJh9d9zZYJPIyTzZkmV3Jk2wDz/M6b6VBnWVGzD9vAbpXV/8JchnYBsTPid6d3c+NZIN6RRHaU/sRyX4ITyzeER98c8e1Lacc2FauiS8c8c1nP4Zm49SZQDlbudX1wcFywInBlJCRNJx0OxGnbUHipLk0mcJlin0MJEJ5LUJH5rJmCUOaM6lidxt6p1MQqeL2hqIpkAEH0b6jSjn3JXJPkz6BCQVqa4/hbegl5skTlMnIOv2+GqgJgHjbWCHlf3ST8EI1JUP80U9636JoM0A/+6EgW7NMPZsVArjjhfPFwfIE7Ujm4+ZJfwmR7ZOw+MRowbaguxoxp6W6lNi3N1pwh1mp7ydbEjPkpuZHYn3lA0HcE9l9rksrLufb2QVQXyuCWFZupMfD+3oGhPc/bck99Cai1PpeZwUQwrXUyYF8G1VMEjhtMSCUJJykaDH9lAcU9/7L9RmX+m0NgJbc2RxQspwXXmNbW0o1GLjQ9ACm5DHLsJmmq++STZFdx0n7PvJgIuB2Bra+8MDWf6284ewvsp4X22mmRALQj9ZM+qhUyOqRvnxO8kgwOVcnkKOBKHEaLJaE5AU5tbQ8oGZegbj8xb4BU2UbYkJR0xDYf0rfY42c7527RGbjKdk5VVz7CSob98cUSIxqL8bOsv3H41Oqskbsp/ChF8u3t1J6p1rCZYJdlR8tXNTFSjlNkXrWu1fG0PA64hAvwQ+zAaXm1xhXQQXi9GnyHw+JlBAtLbruaGgQr4pXAF47CeesB7QJHB9OSqQRg+zwQaxRk/bqySH9df3c59dqojgAWhiNmv2TcpF2gD0nkmBM51iCRWkAKlGLcVlWuP+wgfRdBcgdhPhX3pJw==
    storage_encryption_key: AgBF64zGxqvEd1qy/sGlWQO2nXrhRW7bBH5+Ny3vjYaA4CDc0WdEsoCQ0seteTQfUel7EciHP+2ECKJII/JciySaNkp8/KE5p/tXi4VeR3qfc8ZxfJwV9eBIcUwHiIWuDDRF8/YQKcBG78yqQIPzmE0KnDggeBX+1v3SNCgjpIWT30bTNosWlZbzT69orrn6PllKxuO+9nYIylJ3jAiupx8b0gwTTd9pUQd0Sw6vPsVBX/8YmdrI31YiUnevWMSmkTImRFvw8Hr6JSe2z6OowDEJPmjhROgGg/Kk3n+AIGBfo4R9DuOr4sNKtSy/5DPToZK4z65jtF4n0pjpWzYSzM0kJwXjuD9zF2j8IJC7qRNoJaMgm0DF0YPKclZoegYa0MfbKqGUqgT/CGhROdSmfKdBjEfvGe5IpAcU7A3a/6iBeLT5AQBSrGDDO1jFI8ufag12l00slZLBI+Z88zR6xAKKspZocW+9IngciG3QcUP7hEVYa/H0rQCn4+9gtziFkmQSP77+7356vbifSmQgsJv9i7iymB66kXV1TrgPdxI94rSwy9EkpgrIE8vTHugEDaW4Z3MG0h+T30U7wg+fI1Ka7hhEgnSkebMM6mTAhRWiS/+Ew7/K5XpUQvslnlb0ttMFB4oOykBfcU97WZ2ApidO1qw4kl9TRNOFeQIKe+YGsGLnuMTxI1n11vNCRxNAaY8MeDyMhkwj+Jrl/rHv1xSANvCEpYy+s8g1XQzLyEJxBpssbT/6XMxe7ai+tbxep3VHAAOk47QmEGCWxuw8fsHXQFVP1V3nraNuKThX9JJU8lpVBYwZTDKicQX2iw2kV9I+wybrEaoQ+a21zakvXOnn/Yca4vh+Y2vL62U1FUqyYA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: authelia-secrets
      namespace: ingress-nginx

