---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
spec:
  tls:
    - hosts:
        - login2.desertbluffs.com
  rules:
    - host: login2.desertbluffs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authelia
                port:
                  number: 9091
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: authelia
  namespace: ingress-nginx
spec:
  podSelector:
    matchLabels:
      app: authelia
  ingress:
  - ports:
    - port: 9091
    from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: ingress-nginx
spec:
  selector:
    app: authelia
  ports:
  - name: authelia
    port: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      volumes:
        - name: authelia-config
          projected:
            sources:
              - secret:
                  name: authelia-users
                  items:
                    - key: users.yaml
                      path: users.yaml
              - configMap:
                  name: authelia-custom
                  items:
                    - key: custom.yaml
                      path: custom.yaml
        - name: authelia-secrets
          secret:
            secretName: authelia-secrets
      containers:
        - name: authelia
          image: authelia/authelia:4
          # image: alpine
          env:
            - name: AUTHELIA_JWT_SECRET_FILE
              value: /secrets/jwt
            - name: AUTHELIA_SESSION_SECRET_FILE
              value: /secrets/session
          ports:
            - name: authelia
              containerPort: 9091
          volumeMounts:
            - name: authelia-config
              mountPath: /config
              readOnly: true
            - name: authelia-secrets
              mountPath: /secrets
              readOnly: true
          # command: ["sleep"]
          # args: ["10000000"]
          command: ["authelia"]
          args: ["--config", "/config/custom.yaml"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-custom
  namespace: ingress-nginx
data:
  custom.yaml: |
    ---
    host: 0.0.0.0
    port: 9091
    access_control:
      default_policy: deny
      rules:
        - domain:
            - "*.desertbluffs.com"
          policy: one_factor
    authentication_backend:
      disable_reset_password: true
      file:
        path: /config/users.yaml
        password:
          algorithm: argon2id
          iterations: 1
          salt_length: 16
          parallelism: 8
          memory: 1024
    storage:
      local:
        path: /tmp/db.sqlite3
    session:
      name: authelia_session
      expiration: 1h
      inactivity: 5m
      remember_me_duration:  1M  # 1 month
      domain: desertbluffs.com
    notifier:
      disable_startup_check: true
      filesystem:
        filename: /dev/null
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-users
  namespace: ingress-nginx
spec:
  encryptedData:
    users.yaml: AgCxd5fs1KGFFz8zt/AbA3Rp6TMrPkPyveJeNXeVO+CUMEXCtKziNLL1oSpCwI3uoTRW4oRN91YyOFV3QKFuTmDuAXp/acqvi9S1GwtLwpmic0PTbKb4DxxaJPUmVT4qhXoiBjT+N6UyVZDIpRimlcNxuQS9ha4Sl6vzyKh/6NC6AEZtJEzCX+Ft2sxH2SVkQ3/IQkDooBvL7KOBCteMH1VrHYohA3s/76a2lce3DJfMqUGet3fyCA9ElGXlMfHY9dQGhA85F97pL1O+XNvt7zlvo/e+oCdhmdQZtAxlVdIg+rt+40WUTVkYjylBvLNbV1y7q9GXQB1bImYQ8OAX/m4CBdiSLsNudV4UWxSqAzugIgkBiN9qG58ouCwsuUph4uAhEmg9p8KwmTT63U+YP97Zg+VOw39l9Drhq9s1lUORiKfravz41z1vMKNOqdhpT84XRqZF06Epxzltwq22+hgD9Cnemuk+ZOcsrFh/EbY9saHEoLznwppkamIlwQ0i0+GVyCzg8ISDpVfK6Nxb6naqW96fgAi9eU1U1SlrxffS33jIpBDZHlno9DeBH19ZNa8yQB7QXzn6Q9YmMgiUPuD7u/EwZjT8SYgpUjxyDJNXijL/7erZMJkrlYbhroJFrfMsKmxeAoKfm3eg2Y9Rgg/kCQ83RCQVrJzxFJANSQlodvn0B1JcGZG7+/5WgaCFBEYhChhrmG/qccdNMnX5EBgGWQgiSuHW5sY3schKL1kx0IexxxmTKxoF23MukNjp2vJFJleoJGAoOtLlrNfCXHuo91zfEUgkYHsjhe0D6MJYZ+xXk8lAxcH+h40IYiY+HGIC2HGy59owRGzUV7voB3zhlIV7DKoSFr55Vu9i22p8jjw89XVK/cbfejqXPX0MNXfS6HIoTBzsC3G/AEFix4EalAH9eBYZJCZ2qGS93hk1ZMHwE7ATZ7VWG6adfEpwm1T5/uZihegDDSj/590/1jAyYe3b6g==
  template:
    metadata:
      creationTimestamp: null
      name: authelia-users
      namespace: ingress-nginx
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authelia-secrets
  namespace: ingress-nginx
spec:
  encryptedData:
    jwt: AgBcROb2ccoiJTnP1Copsd1snNKwnjzE5Qb5aIgeOYl1i8/VO2SovRbPAdJST/7Yai8CrGIMSNZTDUoiV6NsHr9I3gsSCiADJ9tJqj8fn5hMbc9iRO5M27U1v7PU/l6sDMnllIH6Xzr5AzIokxTr3dmuH3umHUAQ6FZwrxgGew9p9IM+7k2ZUEIb1UACk31RWsOXZCd0aYDDAODpTurM46N87jfJcqB/rbTp9XK+jbwGkrTzMCTuLk+kNQOX+nA6HYuOPWuHA9AxOHs1OKe0CsS46a8jROnLQtdcbwLn+kxuUy0hW5CSFrbEYrDGTK4fRl0fCZmks7hhEHo0Ic7IIvU8JNvlUQVayffceIzAJlm/WwW+HDA5BI0NpffJjtLYQSvTC7JCAIAWxh6YHZS5KckmPUKWIHqQil4iKQa/oxCpXoKr7/yV+gVqM0HN3za25UJvL+w9j3I4vhWZlsHvM7aqU4pGqqbgOUMW4kSvhhUSEU4Ic14QUppIlrYeC6slPpeiMa/LbyvZyvUCIDiW0pwD9EmU2wMsZArPMgyVXBvZgXDb2ZyvJ7TIjozO8A2Pfw0hZvOAuizUNXGaR1I+iEu5sgA1Uq29UfIb2bCrShNbg5xfu4FhipGWt33yqeua8UQlEGQSCBR85VZ6AMeKuYn8Ei3wA6vFdpeDiPthmcSMyetPe5+9wtMx68Jdh1IrmHeWhZMDoA43aHQKkPqqv4NEFcbXjJCkV4axn0LHof6K0HAQdGTYdOmYGH81HULhB7wM/PUcZvgBqof0lWDMKetpFIPStMb3HwuVn8OgYBuRgARGryIpxWeq4BUUPOwwSAdHIsWPnfKaX/ep+m4HZ6IoUVtkV7hDwTbTDUtUJBjnmg==
    session: AgA66eCZZEzmmDX238sSvUdNH9sQbewMV4UFxslP39+RYF3jo7ZghPR308ijnjujKM4ud2Dq0o1mlS3Q2cUnK8Nb6x/Nc00mm63laZ2BGHEtSpsmaXI4LOw5fxEPQnjUxxytekiB9G11Gun3M4o8QvjwTCG8249jsX3aD2la59TGNZlCleQG+L8w1dD9ftHvVOWCdRi6zYSFAJMgdUPPULbq6uQezc5oLV6d2lrJjcpm6skrgK3jfQJMHuPThCyeTl2xa3qzKHyCSbA0ljkmC2WEyP32fxzrsldDOF2cnVMIcWaoinxQJYhVp5QK2h9z/A27kLk+nkwMn8wIiCulqYlKV2tV96ZhtqPZA+Lj13YVpRCID3qv0V0R7b1fPeaKA8O8FwGCOBurj/qGRI+EzphB+Si9jH8VzcU3lpu5yw4Cywrs2AYyX0Vctx2COgGMRT7trE9DXq9VjBl55WGhKUJm9zTi63nGMgCcrJaP5+pLUgKViiFTLjAah0aniHRsVWiSoae8s4wBHKym2oguFCsdveDeGEUBYEBlRF9zivMg59A7qMWmcHIyP2J+KVXAssbBSPE1oVRja6R+gg2QeWTwT0qBXsnpmHM1syKDoIzM0oDkplusZuOrW1UWB8A6qa8mEuMIdq5hv3Rl/4iHd+/gZ7RBigdRomWXlWczJofagUHG9UeacpOF3x/5Rsp3iRXPVgLAK64Hz800lSSOw+jKcBKlZqPiMWv6wDLe56SBfjIyslZghkbNdjDozuGARTlAYANtpXX7ixVwD73zrOWHQ28/rBjDyj1mMP8u5UEc0G08FX6qq/fzgRMLOoeFuqmWxZMt52DXBJydoOC7x3D7c4JsZ2wpbXasZMXWcmW+vA==
  template:
    metadata:
      creationTimestamp: null
      name: authelia-secrets
      namespace: ingress-nginx
