apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: desertbluffs-com
  namespace: ingress-nginx
  labels:
    use-cloudflare-solver: "true"
spec:
  secretName: desertbluffs-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.desertbluffs.com'
    - desertbluffs.com
