---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: desertbluffs-com-ecdsa
  namespace: ingress-nginx
spec:
  secretName: certificate-desertbluffs-com-ecdsa
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.desertbluffs.com'
    - desertbluffs.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radoncanyon-com
  namespace: ingress-nginx
spec:
  secretName: certificate-radoncanyon-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.radoncanyon.com'
    - radoncanyon.com
