---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: desertbluffs-com
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
spec:
  ingressClassName: external-nginx
  tls:
    - hosts:
        - desertbluffs.com
  rules:
    - host: desertbluffs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ingress-nginx-defaultbackend
                port:
                  number: 80
