apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: default
  annotations:
     "lbipam.cilium.io/ips": "10.0.10.233"
spec:
  selector:
    app: thelounge
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: thelounge
    port: 9000
  - name: identd
    port: 113
