apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: default
spec:
  selector:
    app: thelounge
  type: LoadBalancer
  loadBalancerIP: 10.0.10.233
  externalTrafficPolicy: Local
  ports:
  - name: thelounge
    port: 9000
  - name: identd
    port: 113
