apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: default-dns-ndots
spec:
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
    - apiGroups:
      - apps
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - deployments
      - statefulsets
      - daemonsets
    - apiGroups:
      - batch
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - cronjobs
      - jobs
  reinvocationPolicy: IfNeeded
  mutations:
  - patchType: JSONPatch
    jsonPatch:
      expression: |-
        object.kind == "Pod" ? [
          JSONPatch{
            op: has(object.spec.dnsConfig) ? "replace" : "add",
            path: "/spec/dnsConfig",
            value: {
              "options": [
                {
                  "name": "ndots",
                  "value": "1"
                }
              ]
             }
          }
        ] : object.kind == "CronJob" ? [
          JSONPatch{
            op: has(object.spec.jobTemplate.spec.template.spec.dnsConfig) ? "replace" : "add",
            path: "/spec/jobTemplate/spec/template/spec/dnsConfig",
            value: {
              "options": [
                {
                  "name": "ndots",
                  "value": "1"
                }
              ]
             }
          }
        ] : [
          JSONPatch{
            op: has(object.spec.template.spec.dnsConfig) ? "replace" : "add",
            path: "/spec/template/spec/dnsConfig",
            value: {
              "options": [
                {
                  "name": "ndots",
                  "value": "1"
                }
              ]
             }
          }
        ]
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: default-dns-ndots
spec:
  policyName: default-dns-ndots
  matchResources:
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
