apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: default-dns-ndots
spec:
  matchConstraints:
    resourceRules:
    - apiGroups: ["apps"]
      apiVersions: ["v1"]
      resources: ["deployments", "statefulsets", "daemonsets"]
      operations: ["CREATE", "UPDATE"]
    - apiGroups: ["batch"]
      apiVersions: ["v1"]
      resources: ["cronjobs", "jobs"]
      operations: ["CREATE", "UPDATE"]
  reinvocationPolicy: IfNeeded
  mutations:
  - patchType: "JSONPatch"
    jsonPatch:
      expression: |-
        object.kind == "CronJob" ? [
          JSONPatch{
            op: has(object.spec.jobTemplate.spec.template.spec.dnsConfig) ? "replace" : "add",
            path: "/spec/jobTemplate/spec/template/spec/dnsConfig",
            value: {
              "options": [
                {
                  "name": "ndots",
                  "value": "1"
                }
              ]
             }
          }
        ] : [
          JSONPatch{
            op: has(object.spec.template.spec.dnsConfig) ? "replace" : "add",
            path: "/spec/template/spec/dnsConfig",
            value: {
              "options": [
                {
                  "name": "ndots",
                  "value": "1"
                }
              ]
             }
          }
        ]
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: default-dns-ndots
spec:
  policyName: default-dns-ndots
  matchResources: {}
