---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/cilium.io/ciliumnodeconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  name: netkit-nodes
spec:
  nodeSelector: {}
  defaults:
    bpf-datapath-mode: netkit
