---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -green
images:
- name: docker.io/nlopez/media-toolbox
  newTag: "ae9a8ae"
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: green
