apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-config
  namespace: palworld-ideal-giraffe
data:
  TZ: "UTC"
  SERVER_NAME: "Ideal Giraffe"
  SERVER_DESCRIPTION: "🦒"
  SERVER_PASSWORD: ""
  ADMIN_PASSWORD: ""
  MAX_PLAYERS: "16"
  PORT: "9211"
  QUERY_PORT: "27015"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  REST_API_ENABLED: "true"
  REST_API_PORT: "8212"
  COMMUNITY: "true"
  CROSSPLAY_PLATFORMS: "Steam,Xbox,PS5,Mac"
  ENABLE_PVP: "false"
  DIFFICULTY: "None"
  DEATH_PENALTY: "Item"
  ENABLE_INVADER_ENEMY: "false"
  MULTITHREADING: "false"
  ENABLE_UE4SS: "true"
  ALWAYS_UPDATE_ON_START: "false"
  ## Gameplay rates
  EXP_RATE: "2.0"
  PAL_CAPTURE_RATE: "1.2"
  PAL_SPAWN_NUM_RATE: "1.9"
  PAL_DAMAGE_RATE_ATTACK: "1.4"
  PAL_DAMAGE_RATE_DEFENSE: "1.0"
  PLAYER_DAMAGE_RATE_ATTACK: "1.5"
  PLAYER_DAMAGE_RATE_DEFENSE: "0.8"
  PAL_STOMACH_DECREACE_RATE: "1.0"
  PAL_STAMINA_DECREACE_RATE: "0.1"
  PLAYER_STOMACH_DECREACE_RATE: "1.0"
  PLAYER_STAMINA_DECREACE_RATE: "1.0"
  PAL_EGG_HATCHING_TIME: "0"
  WORK_SPEED_RATE: "2.0"
  DAYTIME_SPEED_RATE: "1.0"
  NIGHTTIME_SPEED_RATE: "1.0"
  COLLECTION_DROP_RATE: "3.0"
  ENEMY_DROP_ITEM_RATE: "3.0"
  ## Base/guild limits
  BASE_CAMP_MAX_NUM: "128"
  BASE_CAMP_WORKER_MAX_NUM: "50"
  GUILD_PLAYER_MAX_NUM: "20"
  DROP_ITEM_MAX_NUM: "5000"
