# Game data volume — proton server downloads ~12-15GB here via SteamCMD
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-data
  namespace: palworld-ideal-giraffe
spec:
  storageClassName: nas1-mtank-iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
