apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: palworld-secrets
  namespace: palworld-ideal-giraffe
spec:
  itemPath: vaults/evjh25ux2mnoufaut6qhvm2pdi/items/ghq5m5sipio5qeshhp7t7z7zb4
