apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: palworld-secrets
  namespace: palworld-ideal-giraffe
spec:
  itemPath: vaults/copxopw5gkuo2m3cv7acvkrfxy/items/i2odfhbwz6d6dm2ykad53uqjva
