apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: overseerr
  namespace: media
spec:
  encryptedData:
    TAUTULLI_API_KEY: AgAno2g+AuD1ZQttsWhiqpuJ1BVbyItci8oNqeSi5lfhF4C4hAtkGsBOlsRoxN+hw0GnBflpNTk+E1ufjazvKb7BpbnPKaOckwupyf6MH2J5B7gc7ohu2lgE67oLkh1OOIFrDautzH/fxL4+P4X4niuzcLc5/xyzdLZe1Iekr9wULwcKHYFUkS9OqarOkpF2TA7RflIMQcDGu2QfmZMmEbm3WcWq0idHH3BKYpGUxlnWgqP4kBehLPxHq+pk4GSI2wvIUx1NfKxSNpZzCmoGKzpwGYOKN7lfU4umCRWry0BYX5kVpAJyZ9xmauOJj4Qto8g3TvzLUrSgohUbqDVxUHcSvw8FSdtP8cb9b0QMzMTBA6M20F0+LVuo6rM8GQe6m7Rp5MqKqeli88GCkmv0P/sPiCaSbT43XuBegXXdGQ9yNOVmmdTVh7L3h8jh5FpsuglY1gUdCbdzpbSXqKTbpEHt+epuL83cUfVuBy8enIQhNUbGQkWA7jGPb96rSFp9R2363FWTDO6wOjPFwagTDcXKrL3YKFQ01HJcumTHP0sQ3blj1WnX8UDQiKIoOyyQZUALCMDWpS9leo9YRfEcu6tzWsoYUqeUZx9axgTxY/Vv0LxrDbZrz3un1CwmGHcTTXxhQhp0VabgzhzBjGAyy4NPgzN6sZ4yec59BKnr3EWeArCpaEKVFKzZUJS3H44OTUaLhpOr7Et8WjesUG5YZguyl7TWjbx2Nq/X1JXSTHowZQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: overseerr
      namespace: media

