apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: media
  labels:
    app: overseerr
spec:
  selector:
    app: overseerr
  ports:
  - name: overseerr
    port: 5055
    protocol: TCP
  