---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: overseerr
  namespace: media
spec:
  serviceName: overseerr
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
      version: v1
  template:
    metadata:
      labels:
        app: overseerr
        version: v1
    spec:
      serviceAccountName: overseerr

      volumes:
        - name: overseerr
          persistentVolumeClaim:
            claimName: overseerr-iscsi-pvc
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: overseerr
          image: lscr.io/linuxserver/overseerr:version-v1.30.1
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: overseerr
              subPath: config
              mountPath: /config
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"
            - name: TAUTULLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: overseerr
                  key: TAUTULLI_API_KEY
            - name: TAUTULLI_URI
              value: "http://127.0.0.1:8181"
          ports:
            - name: http-overseerr
              containerPort: 5055
          readinessProbe:
            tcpSocket:
              port: http-overseerr
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http-overseerr
            initialDelaySeconds: 15
            periodSeconds: 20
