---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: overseerr
  namespace: media
spec:
  serviceName: overseerr
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
      version: v1
  template:
    metadata:
      labels:
        app: overseerr
        version: v1
    spec:
      serviceAccountName: overseerr

      volumes:
        - name: overseerr
          persistentVolumeClaim:
            claimName: overseerr-iscsi-pvc
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: overseerr
          # IMAGE=ghcr.io/linuxserver/overseerr; echo -en "$IMAGE:$(crane ls $IMAGE | sort -V | tail -n1)" | pbcopy
          image: ghcr.io/linuxserver/overseerr:version-v1.33.2
          resources:
            requests:
              cpu: "500m"
              memory: "640Mi"
            limits:
              memory: "640Mi"
          volumeMounts:
            - name: overseerr
              subPath: config
              mountPath: /config
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1001"
            - name: TZ
              value: "America/New_York"
            # - name: TAUTULLI_API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: overseerr
            #       key: TAUTULLI_API_KEY
            # - name: TAUTULLI_URI
            #   value: "http://127.0.0.1:8181"
          ports:
            - name: http
              containerPort: 5055
          # readinessProbe:
          #   tcpSocket:
          #     port: http
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: http
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
