---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sn-server
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: sn-server
  ingress:
    - ports:
        - port: 3000
      from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sn-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sn-server
  template:
    metadata:
      labels:
        app: sn-server
    spec:
      volumes:
        - name: db
          iscsi:
            iqn: iqn.2014-09.com.radoncanyon:nas1:sndb
            targetPortal: 192.168.220.149
            lun: 1
            fsType: ext4
      containers:
        - name: sn-db
          image: mysql:5.7
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
              subPath: var-lib-mysql
          envFrom:
            - secretRef:
                name: server
          env:
            - name: MYSQL_DATABASE
              value: "standard_notes_db"
            - name: MYSQL_USER
              value: "std_notes_user"
        - name: sn-server
          image: nlopez/standardnotes-syncing-server:latest
          command: ["/bin/bash"]
          args:
            [
              "-c",
              "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0",
            ]
          envFrom:
            - secretRef:
                name: server
          env:
            - name: EXPOSED_PORT
              value: "3000"
            - name: RAILS_ENV
              value: "production"
            - name: "RAILS_LOG_TO_STDOUT"
              value: "true"
            - name: DB_PORT
              value: "3306"
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_DATABASE
              value: "standard_notes_db"
            - name: DB_USERNAME
              value: "std_notes_user"
            - name: "DISABLE_USER_REGISTRATION"
              value: "true"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sn-server
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-global-auth: "false"
    external-dns.alpha.kubernetes.io/target: "lga1.desertbluffs.com"
    nginx.ingress.kubernetes.io/proxy-body-size: "10M"
spec:
  tls:
    - hosts:
        - u.desertbluffs.com
  rules:
    - host: u.desertbluffs.com
      http:
        paths:
          - backend:
              serviceName: sn-server
              servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: sn-server
  namespace: default
spec:
  selector:
    app: sn-server
  ports:
    - name: sn-server
      port: 3000
