---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-anime-pv-claim
  labels:
    app: sonarr-anime
    version: v1
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
