service:
  type: ClusterIP
  port: 80
  portName: http

ingress:
  enabled: false

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: rook-ceph-block
  media:
    enabled: true
    existingClaim: media-jellyfin
