service:
  type: ClusterIP
  port: 80
  portName: http
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "bustling-ghost.radoncanyon.com"

ingress:
  enabled: false

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 50Gi
    storageClass: rook-ceph-block
  media:
    enabled: true
    existingClaim: media

resources:
  limits:
    gpu.intel.com/i915: 1

deploymentStrategy:
  type: Recreate

volumes:
- name: config-iscsi
  persistentVolumeClaim:
    claimName: config-iscsi

volumeMounts:
- name: config-iscsi
  mountPath: /config-iscsi

jellyfin:
  args:
  - sleep
  - infinity

image:
  repository: docker.io/alpine
  tag: latest

livenessProbe: 'null'
readinessProbe: 'null'

replicaCount: 1
