service:
  type: LoadBalancer

ingress:
  enabled: true
  className: tailscale
  tls:
  - hosts:
    - jellyfin
  hosts:
  - host: jellyfin.macaroni-pirate.ts.net
    paths:
    - path: /
      pathType: Prefix

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: rook-ceph-block
  media:
    enabled: true
    existingClaim: media-jellyfin
