# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.33.4-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbhydra2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbhydra2
  template:
    metadata:
      labels:
        app: nzbhydra2
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      containers:
      - name: nzbhydra2
        # IMAGE=ghcr.io/linuxserver/nzbhydra2; skopeo --override-os linux list-tags "docker://${IMAGE}" | jq -r '.Tags[]' | sort -V | tail -n1
        image: ghcr.io/linuxserver/nzbhydra2:version-v8.5.4
        # image: alpine
        # command: [ "sleep" ]
        # args: [ "infinity" ]
        volumeMounts:
        - name: config
          mountPath: /config
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/New_York"
        ports:
        - containerPort: 5076
          name: http
        livenessProbe:
          httpGet:
            port: http
            path: /actuator/health/ping
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
