---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.33.4-standalone-strict/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbhydra2-iscsi-pvc
spec:
  volumeName: nzbhydra2-iscsi-pv
  resources:
    requests:
      storage: 2G
  accessModes:
  - ReadWriteOnce
