apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - target:
      kind: CronJob
      name: media-toolbox
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: media-toolbox
        namespace: media
      spec:
        schedule: "* * * * *"
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                - name: curl
                  image: curlimages/curl:latest
                  args:
                  - "-c"
                  - "curl -m 5 -v --socks5-hostname cfwarp.default.svc.cluster.local:1080 https://cloudflare.com/cdn-cgi/trace"
                restartPolicy: OnFailure
