apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: proton-privoxy
  namespace: media
spec:
  encryptedData:
    PVPN_PASSWORD: AgCa6w4EbXtiX+Ia68iMCe5eStt6wi9LeEvC9tDjJNTghQQdwsF2ZvrOJytxuj0kwVOc7MDIcgJssN5Ql+aeIjVFrECU93LhvmrPhrLv89zxiTvPtrWHvEPEoysxzk2zEtrhKQ+3jkPwGsM43FNUT6BJl8NGd4HstBfrY7nZB2zyIvQpdZ2M7g5tt045cc0Vlsg34+aWWpbg8dNC1Irlwnk6SeY7M+XkhBVfhAINhUiyKrA3oYMX5of/aExBVzeVnejDWig4ADj400xpRwxRna3n85yM4WAvbAYowcAgYjJ09Vq11YM4vy1mcIKgY3nEwzy/bAPPzhipDOAqtkrzJaGoCcmuEEg/ofuhDgVbjN0FeqZD46eJow1RVhvpWeISX3O0wq8Pt/BDIXmKGQmsuSw+lXTaVKsPGtFWmTQ4rXDKzNimCUuJJrbejpOg6r4MUmPuVnf2xraGIW6LlW/d9IU1YozT+O3+TWBGxCm/kHnt8TMz6z2cVoN1iifxxONa7wXLICxQkKOVAuAQViF5W3Jvd0aPrtOYkcXIm2NJst5yQWRZTkaBcPutzPFJMKnKLAWh3mK6HX534+FsRFtEiWsmeIwR+bOyyHR1IbVv0jeSWJ02Umdqod76Hnr1+DlZBlDYG3MFZ7kNya+X5eOLTEw/B0kTWk+bQBuqDqAwv3a7XO/G3tOsSsMHuyF3PzbfY2Ri34Xj08vCPboS77BdXu5bnJ6m3jwZL0nMheYsGgUSeA==
    PVPN_USERNAME: AgAvGBZP6sMHedANBXT7nV5iJE9+pknIuYeafEVLRvTtNOUYVzEa0+huDL1hpEeTR4fQtfXoo0edqxvjnUYeNa/hYLV2H1q3kSGM1nLrEI9b6s/pBuL54LwEq1u/z9fWGrMoDxHTFbkey7rwQt3kWc0zZWvb5phaQLgv3A1DlyUCKfOBPQWl4h+kFLhowxoPcEHKTPJLZnZKdSnmXYRi37CTH7FAcBidVQThre2leiMkpTZpmZiAoWg7A2dhjTNFcQp6fIMDUZBCswYn3MxmTy/1T8zu2DmAUjFBTuXL5lSk6H5c92H41NHiWijte/1a0yef89Hn6iMcp43Z25QTiTvdhXQRyC/mV+Zz819peNsSgpFf0cLusB7z582T5qSLry0AlIcyoYPK5aXWBdBou9Z7kA5lzTzfhc4AqPbCWP2GLhNxvML5hjiGw0q3ypKAHsq1OEnzfzWP1j+SVh8QsIqmYJ1o08T2120aS/qumkw4ygWPz71UDqeigB/Hn5vr3/OFJMZIteYY5t8g0hKT110U+T7//4Oc6TGobvgE4oLQADD+lplq8UPRGKcy6yE9LmYEyAqA/xoPAJn6ui8MyX3d+JWnusmo8z+rGG3aN6Iw/xtMBIm5tkb2/U9d3VWZpG6huhu+g4H8d4K25bCQFwSFNNoDMk4HVyquokgwcAcaZIZ1mUzYSFRnJ+FKEk3ixy5FI7/U9CBrKVNW1+Wmx+Vp
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: proton-privoxy
      namespace: media

