# Game data disk for Palworld installation
# iSCSI-backed for performance (~6GB+ for game files)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gamedata-disk
  namespace: palworld-windows
spec:
  storageClassName: nas1-mtank-iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
