# Kubevirt operator Helm values
# Installs the Kubevirt operator, CDI, and related components
imagePullPolicy: IfNotPresent
configuration:
  accessControls: {}
  auditLogs: {}
  defaultRuntimeClass: ""
  developerConfiguration:
    featureGates: []
  diskSettings: {}
  featureRequirements:
    status: disabled
  firmwareConfiguration: {}
  liveMigrationConfiguration:
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 800
    progressTimeout: 1500000000000
  machineType: q35
  network:
    configuration:
      preservePodNetworkError: "true"
    statelessRetry: 1
    statefulRetry: 5
  obsoleteCPUModel: ""
  permittedHostDevices: {}
  pluginConfiguration: {}
  secretTemplateConfiguration: {}
  selinuxLauncherType: ""
  storagePolicyCreateDefaultStorageClass: false
  tlsConfiguration: {}
  virtualMachineOptions: {}
emulatedMachines: [""]
infra:
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
operator:
  logsLevel: "info"
  metricsRelistInterval: 5m
overlays: {}
preUpgradeChecks: {}
runtimeClassConfiguration: {}
