---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freshrss-postgresql
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDUdCKwzI/Vpkh24PXOH+8qvZU5piMST+vuyXtlToA7C2Oa3ZOz21CscDpe9x1eN5w1KTcHLxUCwDE45ysdH8S4/9+lSJ3JVKiIf/mY5YpK4pZYgZGoqxpA02SX1cu6G/jAEqxi1yLg+q5BgS+fZMRcn7ZYGxxr94yPLoCwaSwhkCbaoMtUjRew/L366Ua4d5POL+PneI/Chocm2oljjvWCF3grxYR0bP6B+lcVBzqWri36GpiYSN/fiER0awJnUXpzhcztlhC43ktSoKObeWpUIR9CywvuB6e/njT49mba8O1RYgR4A/ngy4JyjflUqzSVzPNKBZOcocjo5CWopwKVIre2DGH/nsAXvAOem5Q1dwzbDw0fv6S9p+1C1efN/grS6XxuG//7KEiAdOsdeQKXGFCwfYicg4eab+l1xq/YEOH/2jzsUKXf5eaV6RfGp7UaGXI4Dl4xy9zRm95e3TuO9SE9ik9nN4mlRa/J1kMZfpC/ApD/OcxTu58wV5w/IEREziDJfzXlF83syploc+3PUncJ8SLpGg0yssYUDQ3u7jgBlC0f8lArQOPNunsothx3vPyciSA6ScHnsWuGoZIxM4HCN2vp+zn1/LL35gyUSKIBP8QV5VEyWYLxqn+Ocrg5kXl971Ng/sbvTGzB5g3Et+AbdbjqIt/gPl3n5xPYadp9hYdE7dBKPquLvUHCQw8jkrgMV6W5sxyYciuOPJ5Aau7pG8xWMB6NdVxp3V6JMksG+bxBRlPLjEsPH2/Swx7GrJGB5S2pPBgjiJs0j32I
