---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "nlopez@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyID: AKIAX6OKM7CDHRHPJPDT
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: secret-access-key
