apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "nlopez@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-private-key
    dns01:
      providers:
      - name: cloudflare
        cloudflare:
          email: y26fpcpdk9@liamekaens.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
