apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgB3e7xD6+V6dcIPQTA0Vqc0ikZ3Z3tYbsVXbhjOce+Pb9Y50HWb3wt3IEgZ9yVsZrMzT9QWvM3WvWpnylAPgDL+GHOENmORKQP/4hnDZleaJEVqqr2pR9C4jYvlEu7Ztd5dvikwgZZ230ilC2rcicR0RL+olRFzVuZvQxwhB3HLGv22fft0y8hm0KUxuFfvKd93O3U8pPMsKKSTKd8tR/dzQjbiSjo2PUCvoW8hnOQLMnWEFYG3QuRN1BlX+pCVHtTV3ScsawV5kSjcXzkv/tyZNfZURaVwpMFe669QCNs7NuD10em3ahy06KgLsIvHPm3ul8cjzPmzeKj/5mRg8x3PRPm7m7ujSno0rx/NyiLflq3tDqG336SG5WyjqYNlXqPPZSUs8DlwK97EG3bL2fq9FwIRwWyPm/eIQ5Hv1Cesa8jyb5D5aLwe4MryBxigV8iVAG33mtXErNjgivY5bk8Ru51cYvJ/Z2o4ChDe9rdafCaNbIwQ/LsY7LrX+bxCSJZbTyiHJzuhjDLJRVLPmT9vJnz+f5DCJbqvjLjO2NmgxnwqXiIwZR90wJ/RA3FAWn2YfSbt0Mr8Qgs0AhstnRysuh2qWx5P5zLwYQBFdoC+Vzsixtw1+6wB07Eeg5a+h3hOdSkku5mMy0gR5VL976mvUKYFxv175X1GO8Wkz71jVJZRD3+BfgqhxOyGEdX9MPLbWj30Yz5Cv+vuQ+aBvnuynMIHuvAHkbpTY9/mi0lD9DLtE536dEjN
