apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    secret-access-key: AgBqWZxTm2eF9Ygbl0uKrL44pL7DwFXiAaaBgtSnqrjqLeLsCVNzz0Cgtki7UlRRhD3xAkhQcw7s62kMOL42O1yeOPFREt0WaEBQ5OETIkB5p90fpD3htOPXuT8NtNe07ySLJostUMnZXXMe2yKCQxlgTKC11IW9vERLoKctfuiQJZoL22S0TjxoWo1UBx+OHYaDfzHU4Z6wnHuzsqDKXjM2wHHHw1BNBvu0YvQOwgGd0UpUyoC7wniab3ELO5K0vkyQFt+CS3OULCoSA2MdoA3Lvj66xDtSGLU0brYc6EPM9lUXUBg3WiPoJecp1xWaynn6zI6Fw61vfdNQnvfFy3QwsPZGtUdl4zwsy9yBqZ6usoG79Ac/p2Eu9+bqXlqz2S280gztAAeRe65cGDAf+cIi9rlAxCiIhgWpO/0wgYyGDBNPzRtOPTGEkUrZNID661wL+XAvxfjCghVQ7FPxdoZ51Hy48v0uwsooCP2ZQSvWTegXUBYPVLaE3gUyl+lu0xoABB4si1zdc/VnMvt3WrDzYzu0teeh1qovnoZdkw7jiQ2mZ6D8VoJaRlKJjxUdT8aZDoZRt74E1YsH7wf9/tAQAwarBMIWaObrex3tNzVD2EowKiip4pP723LJiirif37a3Fs0BShat4rEUueC5z5j2J7AJanJk/1s/Y8uceRKyI1CqMLanWu6YN7gFz9c/9D5S87+ihMmbrpNn+t1p1q8ueiEYeDCFQfOn8Rdr9NfJFVFJfC/E9ci
  template:
    metadata:
      creationTimestamp: null
      name: route53-credentials-secret
      namespace: cert-manager
