---
apiVersion: apps/v1
kind: CronJob
metadata:
  name: toolbox-cron
  namespace: media
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: toolbox
            command: ["/bin/bash"]
            args:
            - --login
            - -x
            - /media/youtube/scripts/livechat.sh
            env:
            - name: HOME
              value: /home/user
