# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/tailscale.com/connector_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: lga1-routes
spec:
  hostname: lga1-routes
  subnetRouter:
    advertiseRoutes:
    - 10.43.64.0/24
    - 192.168.222.0/24
