# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/tailscale.com/proxygroup_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: mercury
spec:
  type: egress
  tags:
  - "tag:k8s"
  - "tag:home"
  - "tag:lga1"
  replicas: 2
