# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/tailscale.com/proxyclass_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: heimdall-direct
spec:
  staticEndpoints:
    nodePort:
      ports:
      - "31667-31680"
      selector:
        kubernetes.io/os: linux
