apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: heimdall-direct
spec:
  staticEndpoints:
    nodePort:
      ports:
      - port: 31667
        endPort: 31680
      selector:
        kubernetes.io/os: linux
