apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internet
  annotations:
    lbipam.cilium.io/ips: ""
spec:
  gatewayClassName: internet
  addresses:
    - type: IPAddress
      value: 10.43.64.20
  listeners:
    - name: http
      protocol: HTTP
      port: 80
