apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internet
  annotations:
    lbipam.cilium.io/ips: "10.43.64.20"
spec:
  gatewayClassName: internet
  addresses: []
  listeners:
    - name: http
      protocol: HTTP
      port: 80
